### ISSUE TITLE
Busca Avançada - desabilitar antiga

### ISSUE THREAD

**Issue by pintoros** [bireme/iahx-opac#104]
Desabilitar a opção de busca avançada enquanto não houver alteração da interface

**Comment by marcioalvessilva** [comment]
botão foi comentado 
https://github.com/bireme/mockups/commit/e43ac24dc13e2dc322734fc0ed6ffedb57af55a1#diff-a3e49808bfabf2e0e0fa0ef4eaedce07R23

**Comment by viniciusandrade** [comment]
Desabilitado no template.

**Comment by pintoros** [comment]
Devido a não previsão da nova interface avançada, solicito reabilitar essa modalidade no iAHx.
Obrigada

**Comment by viniciusandrade** [comment]
Link retornado.
