### ISSUE TITLE
Erro no envio por e-mail

### ISSUE THREAD

**Issue by pintoros** [bireme/iahx-opac#108]
A nova interface apresenta erro no recurso envio por e-mail. Após preencher o formulário de envio a seguinte mensagem aparece:
![image](https://user-images.githubusercontent.com/29313904/64267537-f8120b00-cf0c-11e9-88b4-6f9ecc57dfda.png)

**Comment by viniciusandrade** [comment]
@pintoros 

Ajuste realizado no sistema. Favor realizar novo teste e informar se esta OK.

Obrigado
