### ISSUE TITLE
Pesquisa DeCS/MeSH

### ISSUE THREAD

**Issue by pintoros** [bireme/iahx-opac#110]
Na nova interface a pesquisa DeCS/MeSH não mantém a pesquisa do usuário na caixa de busca.
O comportamento normal é manter e somar o resultado com o descritor ou descritores selecionados nesta modalidade.

Uma vez que a caixa de busca agora faz parte da modalidade pesquisa DeCS/MeSH, a interação entre ela e os descritores de assunto indicados deveria ser permitida.

**Comment by pintoros** [comment]
Sobre este chamado, solicito excluir a caixa de busca iAHx da interface Pesquisa DeCS/MESH, 
Motivos:
- Não há interação entre esta caixa e a busca no DeCS nesta modalidade
- Duas caixas de busca com propósitos diferentes na mesma interface confundem o usuário
![Pesquisa DeCS](https://user-images.githubusercontent.com/29313904/80406710-e1089a80-889a-11ea-85ce-4b815be64619.jpg)

**Comment by viniciusandrade** [comment]
@pintoros 
Caixa de busca desabilitada para página **Localizar descritor de assunto.**
