### ISSUE TITLE
Opção exportar referências - erro de conteúdo e limite

### ISSUE THREAD

**Issue by pintoros** [bireme/iahx-opac#114]
A opção exportar referências apresenta erro:

1) Selecionada a opção todas as referências, só são exportadas entre 200-250 referências

2) O conteúdo exportado não obedece a ordem do resultado
Exemplo:
ti:dengue brasil aedes = 430 referências  hoje
- a última exportada foi a referência - Epidemia de febre clássica de dengue causada pelo sorotipo 2 em Araguaina, Tocantins, totalizado 212 referências, porém o número desta referência na interface é 410

- a antepenúltima referencia exportada foi - Uso de método multivariado para construção de um indicador para ocorrência de dengue no município do Rio de Janeiro, períodos de 2001-2002 e 2007-2008, o número desta referência na interface é 147

3) Quando selecionado o intervalo últimos 10 anos o resultado na interface aparece correto, porém no arquivo de exportação aparecem referências de 2003 mesclada ao resultado????

**Comment by viniciusandrade** [comment]
@pintoros 
Revisei o código e acredito que agora o sistema esta novamente exportando corretamente o conjunto de referências. Favor realizar novo teste.
