### ISSUE TITLE
Busca no iAHx não mostra localização/responsável pelo documento

### ISSUE THREAD

**Issue by alvesmarilda** [bireme/iahx-opac#116]
Na pesquisa iAHx não é possível localizar a biblioteca responsável pelo documento.

Exemplos: 
Gerontologia educacional e educação gerontológica: subsídios bibliográficos (1976 - 1996). v. I / Educational gerontology and gerontological education: bibliographical subsidies (1976-1996). v. I Sobral, Benigno. Rio de Janeiro; Real Engenho; 2016. 239 p. (Temas reais).
Monografia em Português | LILACS | ID: biblio-871470

Geriatria e cuidados paliativos / Geriatrics and palliative care
Barbosa, Atílio Gustavo Blanco; Caldeira, Sandriani Darine.
São Paulo; Medcel; 2012. 101 p. graf, tab.
Monografia em Português | LILACS, AHM-Acervo, TATUAPE-Acervo | ID: lil-667850

Obrigada

**Comment by viniciusandrade** [comment]
Informação de biblioteca responsável e localização incluídas no novo template.  (2ba485586030b84e339478ba9ada884a2151c13c)
