### ISSUE TITLE
Campo Assunto - Apresenta inconsistência

### ISSUE THREAD

**Issue by pintoros** [bireme/iahx-opac#118]
O campo Assunto que aparece com link para o DeCS, abaixo do resumo dos documentos, apresenta inconsistência, ora informa que a descrição não está disponível, ora informa uma descrição que não tem nada a ver com o descritor selecionado. 

![screenshot-pesquisa bvsalud org-2019 09 12-14_40_59](https://user-images.githubusercontent.com/29313904/64813611-211f4500-d578-11e9-9d01-c3b0e3745e61.png)
![screenshot-pesquisa bvsalud org-2019 09 12-14_43_16](https://user-images.githubusercontent.com/29313904/64813612-211f4500-d578-11e9-8a05-6474e42ea9ac.png)
![screenshot-pesquisa bvsalud org-2019 09 12-14_46_50](https://user-images.githubusercontent.com/29313904/64813613-211f4500-d578-11e9-808a-0ec52b107f48.png)

**Comment by viniciusandrade** [comment]
@pintoros 

Apresentação das definições revisada, favor verificar e re-abrir em caso de erro.

Obrigado.

**Comment by pintoros** [comment]
Os descritores Masculino e Feminino ainda não apresentam a definição. Não sei informar se isso ocorre com mais algum descritor.

![screenshot-pesquisa bvsalud org-2019 09 16-17_24_57](https://user-images.githubusercontent.com/29313904/64994339-c0ad4200-d8ae-11e9-8877-dc0b8c01162b.png)
![screenshot-pesquisa bvsalud org-2019 09 16-17_30_16](https://user-images.githubusercontent.com/29313904/64994342-c1de6f00-d8ae-11e9-9dff-a786ea421cb0.png)

**Comment by viniciusandrade** [comment]
Estes descritores não possuem realmente definição no DeCS conforme pode ser observado nos links abaixo:

http://decs.bvsalud.org/cgi-bin/wxis1660.exe/decsserver/?IsisScript=../cgi-bin/decsserver/decsserver.xis&search_language=p&interface_language=p&previous_page=homepage&task=exact_term&search_exp=MASCULINO

http://decs.bvsalud.org/cgi-bin/wxis1660.exe/decsserver/?IsisScript=../cgi-bin/decsserver/decsserver.xis&search_language=p&interface_language=p&previous_page=homepage&task=exact_term&search_exp=FEMININO

**Comment by pintoros** [comment]
Tem razão, somente nota de indexação.
Obrigada.




Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:2adaebf1-bcdf-495a-99d4-c5e881a831ab]

________________________________
De: viniciusandrade <notifications@github.com>
Enviado: segunda-feira, 16 de setembro de 2019 18:29
Para: bireme/iahx-opac <iahx-opac@noreply.github.com>
Cc: Pinto, Rosemeire (BIR) <pintoros@paho.org>; State change <state_change@noreply.github.com>
Assunto: Re: [bireme/iahx-opac] Campo Assunto - Apresenta inconsistência (#118)


Estes descritores não possuem realmente definição no DeCS conforme pode ser observado nos links abaixo:

http://decs.bvsalud.org/cgi-bin/wxis1660.exe/decsserver/?IsisScript=../cgi-bin/decsserver/decsserver.xis&search_language=p&interface_language=p&previous_page=homepage&task=exact_term&search_exp=MASCULINO<https://nam05.safelinks.protection.outlook.com/?url=http%3A%2F%2Fdecs.bvsalud.org%2Fcgi-bin%2Fwxis1660.exe%2Fdecsserver%2F%3FIsisScript%3D..%2Fcgi-bin%2Fdecsserver%2Fdecsserver.xis%26search_language%3Dp%26interface_language%3Dp%26previous_page%3Dhomepage%26task%3Dexact_term%26search_exp%3DMASCULINO&data=02%7C01%7Cpintoros%40paho.org%7Cd4d3d479302046e554e508d73aecf1cb%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C1%7C637042661671082654&sdata=s%2F2LPPDIjzz3fGQ4eJqvBwgRC5pdyfPGiyRC0fgL5q4%3D&reserved=0>

http://decs.bvsalud.org/cgi-bin/wxis1660.exe/decsserver/?IsisScript=../cgi-bin/decsserver/decsserver.xis&search_language=p&interface_language=p&previous_page=homepage&task=exact_term&search_exp=FEMININO<https://nam05.safelinks.protection.outlook.com/?url=http%3A%2F%2Fdecs.bvsalud.org%2Fcgi-bin%2Fwxis1660.exe%2Fdecsserver%2F%3FIsisScript%3D..%2Fcgi-bin%2Fdecsserver%2Fdecsserver.xis%26search_language%3Dp%26interface_language%3Dp%26previous_page%3Dhomepage%26task%3Dexact_term%26search_exp%3DFEMININO&data=02%7C01%7Cpintoros%40paho.org%7Cd4d3d479302046e554e508d73aecf1cb%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C1%7C637042661671092653&sdata=6oq6MnxbzeP%2BjbDSN%2Feasl1b5PwaJ8Qj0fGVSrDnX8k%3D&reserved=0>

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fiahx-opac%2Fissues%2F118%3Femail_source%3Dnotifications%26email_token%3DAG7UW4GSE64KKWZNPBQEY2DQJ73DFA5CNFSM4IWIRQHKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD62SPDY%23issuecomment-531965839&data=02%7C01%7Cpintoros%40paho.org%7Cd4d3d479302046e554e508d73aecf1cb%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C1%7C637042661671092653&sdata=Q62NcRTX82YodgOJXTWV3EkHpTdwRGdlM0yrjeQSJ0k%3D&reserved=0>, or mute the thread<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4AQOWWDHXJ3ZL6G4OLQJ73DFANCNFSM4IWIRQHA&data=02%7C01%7Cpintoros%40paho.org%7Cd4d3d479302046e554e508d73aecf1cb%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C1%7C637042661671102650&sdata=IhDUYUEQZFceUQqIsokL3FnawQd8DnV311g72IbqHOw%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.
