### ISSUE TITLE
Navegador IE comandos não funcionam

### ISSUE THREAD

**Issue by alvesmarilda** [bireme/iahx-opac#119]
Comandos que não funcionam:

![screenshot-pesquisa bvsalud org-2019 09 13-17_10_45](https://user-images.githubusercontent.com/38661168/64892005-bb02f280-d649-11e9-8886-e022b46c81dd.png)
![screenshot-pesquisa bvsalud org-2019 09 13-17_07_55](https://user-images.githubusercontent.com/38661168/64892011-c1916a00-d649-11e9-9d0f-cbdc23384e6c.png)
![screenshot-pesquisa bvsalud org-2019 09 13-17_07_21](https://user-images.githubusercontent.com/38661168/64892024-c5bd8780-d649-11e9-8b92-4c004cac571d.png)

Enviar resultado por email funcionou!

Obrigada!

**Comment by viniciusandrade** [comment]
@marcioalvessilva poderia verificar por favor? Obrigado.

**Comment by viniciusandrade** [comment]
Testes realizados.
