### ISSUE TITLE
Pesquisa Avançada - Operadores não funcionam

### ISSUE THREAD

**Issue by pintoros** [bireme/iahx-opac#120]
Operadores OR e AND NOT entre as linhas não funcionam. 

Feedback de usuário abaixo

_"OR and AND NOT buttons are not working in Advanced Search. The results show AND no matter what is selected with those buttons."_

**Comment by renatomurasaki** [comment]
Assunto sendo tratado no issue #211

**Comment by pintoros** [comment]
OK Renato. Alguma possibilidade de ajuste até 4a feira?
Gostaria de tratar no Encontro da RefNet que teremos nessa data.

Obrigada



Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:e21fc0fb-faef-4c3d-bea7-b84daf6ea52e]

________________________________
De: Renato Murasaki <notifications@github.com>
Enviado: segunda-feira, 5 de outubro de 2020 11:04
Para: bireme/iahx-opac <iahx-opac@noreply.github.com>
Cc: Pinto, Rosemeire (BIR) <pintoros@paho.org>; Author <author@noreply.github.com>
Assunto: Re: [bireme/iahx-opac] Pesquisa Avançada - Operadores não funcionam (#120)


Assunto sendo tratado no issue #211<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fiahx-opac%2Fissues%2F211&data=02%7C01%7Cpintoros%40paho.org%7C09f3fb2404ad41ab73d708d86937a53b%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637375034994471447&sdata=kKpiMfbQPaUwRwgU3rdALc4uPzLOWicps%2FYYND6HjvY%3D&reserved=0>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fiahx-opac%2Fissues%2F120%23issuecomment-703654335&data=02%7C01%7Cpintoros%40paho.org%7C09f3fb2404ad41ab73d708d86937a53b%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637375034994481444&sdata=EyJBqEhI02F1qik%2FzrbgdIkEMmldj%2FguZEDxxuSpQMU%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4EK3GA5P4S7J3WW2XTSJHHATANCNFSM4IXFOEFA&data=02%7C01%7Cpintoros%40paho.org%7C09f3fb2404ad41ab73d708d86937a53b%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637375034994481444&sdata=uRRM7VRXhdAGUQPD6sDTst5cdXWEhi8%2BrToY%2B4AoQlI%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.
