### ISSUE TITLE
Incluir variável/parâmetro nas chamadas ao iAHx para identificar ações provenientes de usuário da MinhaBVS

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/iahx-opac#124]
bireme/plat-serv-bvs#221

**Comment by wilsonmoura** [comment]
@viniciusandrade conforme conversamos, criamos o cookie `userID` para ser usado no tracker do Google Analytics usado no iAHx.

**Comment by viniciusandrade** [comment]
Conforme verificado será necessário a atualização dos códigos do Google Analytics utilizados no IAHX para a nova versão (ga.js -> analytics.js)  incluindo todos os eventos para ser possível adicionar o código de usuário.

https://developers.google.com/analytics/devguides/collection/upgrade/reference/gajs-analyticsjs

**Comment by viniciusandrade** [comment]
Implementado e em produção. 

@renatomurasaki conforme verificamos foi necessario criar uma visualização adicional no GA para visualizar os relatórios com esta integração.
