### ISSUE TITLE
Na interface antiga, no formato de saída onde existe um link no título de revista, ao clicar nele abre um pop up em branco onde não retorna nenhuma informação

### ISSUE THREAD

**Issue by marcoslmori** [bireme/iahx-opac#125]
Aparentemente, após a instancia de produção ser implementada o protocolo ssl, no iahx que tem a interface antiga, no formato de saída onde existe um link no título de revista, ao clicar nele abre um pop up em branco onde não retorna nenhuma informação.  No entanto, se você clicar para abrir em outra aba, a requisição é feita para o portal de revistas e retorna a informação desejada. 

Exemplos
https://pesquisa.bvsalud.org/economia/
https://pesquisa.bvsalud.org/enfermeria/
https://pesquisa.bvsalud.org/saudepublica/
e etc

1
![image](https://user-images.githubusercontent.com/10047460/65884366-1eda2a80-e36f-11e9-8565-b1246fbbb466.png)

---------------
2
![image](https://user-images.githubusercontent.com/10047460/65884311-036f1f80-e36f-11e9-988c-8267cd10901b.png)

---------------
Na interface nova esse mesmo link tem um comportamento de fazer a requisição na mesma aba e sem pop up e funciona normalmente. 

![image](https://user-images.githubusercontent.com/10047460/65884475-4df09c00-e36f-11e9-8944-5595a50b62ad.png)
------------------------

![image](https://user-images.githubusercontent.com/10047460/65884510-5cd74e80-e36f-11e9-9072-35635711db74.png)

**Comment by marcoslmori** [comment]
Foi solicitado para que fosse implementado o protocolo ssl também no portal de revistas, mas não será possível, veja avaliação da nossa infraestrutura: 

"A instancia portal.revistas.bvs.br nao suporta SSL devido a obsolescência do app e do ambiente onde encontra-se instalado" [ocomon 6633]

**Comment by viniciusandrade** [comment]
Alterei os templates da versão anterior do IAHX para abrir o Portal de Revistas e o Centros em nova aba do navegador. 

Este ajuste resolve este problema para todas as intâncias que não possuem o template **result-inc-source.html** e **result-inc-location.html**  customizados, ou seja, alterados dentro da pasta **custom/**

**Comment by marcoslmori** [comment]
para documentar para  as instancias que são customizadas.  renomear o result-inc-source.html  para result-inc-source.html-old
