### ISSUE TITLE
Ordem dos filtros iAHx

### ISSUE THREAD

**Issue by pintoros** [bireme/iahx-opac#128]
Com base nos indicadores e solicitação de usuários via feedback, solicito alterar os clusters abertos na interface iAHx para a seguinte estrutura:

**Base de dados
Assunto
Tipo de estudo
idioma**

*Texto completo e Intervalo de ano permanecem como estão.
País como assunto fica nos adicionais

**Comment by viniciusandrade** [comment]
Ajuste realizado na configuração.
