### ISSUE TITLE
No formato detalhado, a opção de mudar de idiomas não se comporta corretamente

### ISSUE THREAD

**Issue by marcoslmori** [bireme/iahx-opac#14]
Testado no IE, Firefox e Chrome.

Cenario: no resultado de uma pesquisa, você clica no título e irá mostrar o formato detalhado.  No formato detalhado, voce muda de idioma mas a interface não muda e nem o destaque dos idiomas, apesar que na url o parametro lang muda para o selecionado

Veja os destaques da  imagem. . 

![image](https://cloud.githubusercontent.com/assets/10047460/16688526/d53d4766-44f4-11e6-9094-7449b43e8ae7.png)

**Comment by viniciusandrade** [comment]
Corrigido em https://github.com/bireme/iahx-opac/commit/ad4095513d8b9c5764f0a2e334adec4839cfd372
