### ISSUE TITLE
RIS export quantity is different of the search result

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/iahx-opac#149]
Example:
The result of the following search retrieves 759 records in GIM search interface:
`((ti:( (gender-nonconform* OR gender-non-conform* OR   trans-female* OR trans-male* OR trans-man OR trans-men OR trans-women OR trans-woman OR trans-girls OR trans-boys OR  trans-population* OR trans-patient* OR trans-participant* OR trans-subject* OR trans-adolescent* OR trans-teen* OR trans-child* OR trans-individual* OR trans-people OR trans-person* OR trans-youth* OR  agender OR  bicurious OR  bigender* OR  bisexual* OR  cross-sex OR  crossgender OR  dsd OR  gay OR  gays OR  gender-change OR  gender-crossing OR  gender-dysphori* OR  gender-fluid* OR  gender-identit* OR  gender-incongruen* OR  gender-minorit* OR  gender-neutral OR  gender-queer OR  gender-transition* OR  gender-varian* OR  genderless OR  genderqueer* OR  glb* OR      heteroflexible OR  homosexual* OR  intersex* OR  lesbian* OR  lesbigay* OR  lgb* OR     "men who have sex with men" OR  mostly-heterosexual OR  msm OR  msmw OR  nonbinary OR  non-binary OR  nonheterosexual OR  non-heterosexual OR  queer OR  queers OR  "same gender loving" OR  same-sex-couple* OR  same-sex-relations* OR  same-sex-attract* OR  sexual-identit* OR  sexual-minorit* OR  sexual-orientation* OR  sexual-preference* OR  sgm OR  third-gender* OR  transboy* OR  transex* OR  transfeminine OR  transgender* OR  transgirl* OR  transman OR transmen OR  transmasculine OR  transsex* OR  trans-sex* OR  trans-spectrum OR  transwoman OR transwomen OR  two-spirit* OR  "women loving women" OR  "women who have sex with women" OR  wsm OR  wswm) AND (afghan* OR algeria* OR bahrain* OR djibouti* OR egypt* OR iran* OR iraq* OR jordan* OR kuwait* OR lebanon OR lebanese OR libya* OR mauritania* OR morocco OR morroccan* OR oman* OR palestin* OR pakistan* OR qatar* OR saudi-arabia* OR saudi* OR somalia* OR sudan* OR syria* OR tunisia* OR "united arab emirates" OR emirati* OR yemen* OR middle-east* OR north-africa* OR "west bank" OR gaza* OR mena OR maghreb* OR israel* OR arab* OR druze OR kabul OR algiers OR manama OR djibouti OR cairo OR tehran OR baghdad OR amman OR "Kuwait City" OR beirut OR tripoli OR nouakchott OR rabat OR muscat OR ramallah OR jerusalem OR islamabad OR doha OR riyadh OR mogadishu OR khartoum OR damascus OR tunis OR "Abu Dhabi" OR "sana'a" OR sanaa)) OR ab:( (gender-nonconform* OR gender-non-conform* OR   trans-female* OR trans-male* OR trans-man OR trans-men OR trans-women OR trans-woman OR trans-girls OR trans-boys OR  trans-population* OR trans-patient* OR trans-participant* OR trans-subject* OR trans-adolescent* OR trans-teen* OR trans-child* OR trans-individual* OR trans-people OR trans-person* OR trans-youth* OR  agender OR  bicurious OR  bigender* OR  bisexual* OR  cross-sex OR  crossgender OR  dsd OR  gay OR  gays OR  gender-change OR  gender-crossing OR  gender-dysphori* OR  gender-fluid* OR  gender-identit* OR  gender-incongruen* OR  gender-minorit* OR  gender-neutral OR  gender-queer OR  gender-transition* OR  gender-varian* OR  genderless OR  genderqueer* OR  glb* OR      heteroflexible OR  homosexual* OR  intersex* OR  lesbian* OR  lesbigay* OR  lgb* OR     "men who have sex with men" OR  mostly-heterosexual OR  msm OR  msmw OR  nonbinary OR  non-binary OR  nonheterosexual OR  non-heterosexual OR  queer OR  queers OR  "same gender loving" OR  same-sex-couple* OR  same-sex-relations* OR  same-sex-attract* OR  sexual-identit* OR  sexual-minorit* OR  sexual-orientation* OR  sexual-preference* OR  sgm OR  third-gender* OR  transboy* OR  transex* OR  transfeminine OR  transgender* OR  transgirl* OR  transman OR transmen OR  transmasculine OR  transsex* OR  trans-sex* OR  trans-spectrum OR  transwoman OR transwomen OR  two-spirit* OR  "women loving women" OR  "women who have sex with women" OR  wsm OR  wswm) AND (afghan* OR algeria* OR bahrain* OR djibouti* OR egypt* OR iran* OR iraq* OR jordan* OR kuwait* OR lebanon OR lebanese OR libya* OR mauritania* OR morocco OR morroccan* OR oman* OR palestin* OR pakistan* OR qatar* OR saudi-arabia* OR saudi* OR somalia* OR sudan* OR syria* OR tunisia* OR "united arab emirates" OR emirati* OR yemen* OR middle-east* OR north-africa* OR "west bank" OR gaza* OR mena OR maghreb* OR israel* OR arab* OR druze OR kabul OR algiers OR manama OR djibouti OR cairo OR tehran OR baghdad OR amman OR "Kuwait City" OR beirut OR tripoli OR nouakchott OR rabat OR muscat OR ramallah OR jerusalem OR islamabad OR doha OR riyadh OR mogadishu OR khartoum OR damascus OR tunis OR "Abu Dhabi" OR "sana'a" OR sanaa))))`

However, the RIS file generated has 760 records (see attachment renamed to TXT extension)
[export (4).ris.txt](https://github.com/bireme/iahx-opac/files/4198516/export.4.ris.txt)
)

**Comment by viniciusandrade** [comment]
Correção aplicada e testes realizados no âmbito do WHO COVID.
