### ISSUE TITLE
Erro de visualização de registro com resumo em mobile

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/iahx-opac#156]
![erro-resumo-mobile](https://user-images.githubusercontent.com/349287/77356926-03e8e180-6d26-11ea-9056-c50397dd92cb.jpg)

**Comment by viniciusandrade** [comment]
Conforme indicado pelo @marcioalvessilva foi adicionado div clearfix conforme exemplo abaixo:
```
 <div class="social">
...
    <div class="clearfix"></div>
</div>
```
@renatomurasaki, ajuste em produção. Agradeço, quando puder,  realizar novo teste pois no meu celular o problema não era apresentado.

**Comment by marcioalvessilva** [comment]
Teste realizado!
Problema foi solucionado

**Comment by viniciusandrade** [comment]
:+1:
