### ISSUE TITLE
Registros LLXP que estão no Fi-admin não estão sendo recuperados no iAHx:

### ISSUE THREAD

**Issue by alvesmarilda** [bireme/iahx-opac#159]
Segue alguns exemplos de registros que estão no Fi-admin como LLXP e não aparecem na busca iAHx:

Fi-admin
[](https://fi-admin.bvsalud.org/bibliographic/edit-analytic/1054885)
1054885	An. bras. dermatol; 94 (6), 2019 | Primary diffuse cutaneous plasmacytoma: when a correct clinico-pathologic approach is mandatory for the patient's health,	**LILACS-Express**	

**No iAHx recupera somente Medline**
Primary diffuse cutaneous plasmacytoma: when a correct clinico-pathologic approach is mandatory for the patient's health.
Broggi, Giuseppe; Martino, Enrica; Calafiore, Valeria; Caltabiano, Rosario.
An Bras Dermatol ; 94(6): 767-769, 2019.
Artigo em Inglês | **MEDLINE | ID: mdl-31789243**

Não recupera no iAHx
[](https://fi-admin.bvsalud.org/bibliographic/edit-analytic/1054633)
1054633	Acta bioeth; 25 (2), 2019 | Perspectiva bioética sobre el aborto en Argentina a través del aporte del cine	**LILACS-Express**	

**Histórico dos  registros : Registro criado: 25 de Março de 2020 às 09:00 pelo usuário import**
Obrigada

**Comment by falbrito** [comment]
Verificado e registros estão disponíveis.

https://pesquisa.bvsalud.org/portal/resource/pt/biblio-1054885
https://pesquisa.bvsalud.org/portal/resource/pt/biblio-1054633
