### ISSUE TITLE
Criar opção "Buscar no Google"

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/iahx-opac#163]
- Adicionar botão na página de detalhes que monta link para busca no Google com o título da referência atual.

- Criar parâmetro que permita habilitar/desabilitar este botão no config

**Comment by viniciusandrade** [comment]
Disponível no ambiente de testes da interface OMS COVID-19.

**Comment by renatomurasaki** [comment]
@viniciusandrade fantastico! Para melhor a qualidade da busca, por favor, coloque o título entre aspas

**Comment by viniciusandrade** [comment]
@renatomurasaki OK,ajuste realizado.

**Comment by renatomurasaki** [comment]
@viniciusandrade testado e OK. Ficou muito legal o botão com o G estilizado. Pode colocar em produção.

**Comment by viniciusandrade** [comment]
@renatomurasaki ajuste em produção para interface OMS COVID.
