### ISSUE TITLE
Resultado de busca no iAHx mostra somente 20 registros

### ISSUE THREAD

**Issue by alvesmarilda** [bireme/iahx-opac#164]
Colegas,

O resultado da busca no iAHx não está permitindo rolagem de páginas para visualização de outros registros ou o comando Mostrar:  | 50 | 100

Exemplo: https://pesquisa.bvsalud.org/portal/?lang=pt&home_url=http%3A%2F%2Flilacs.bvsalud.org&home_text=Pesquisa&q=cancer+mama&submit=

Obrigada
Marilda

**Comment by viniciusandrade** [comment]
Marilda,
Conforme conversamos o problema ocorreu durante algumas horas do dia 07/04 e logo que notei apliquei a correção. 

Correção feita em 774a822837893e0e2f6700f30012c70bdc43e139
