### ISSUE TITLE
Implementar ordenamento do resultado de busca por data de entrada na base de dados

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/iahx-opac#165]
É possível adicionar o campo de entrada na base de dados para ordenamento do resultado de busca, de maneira a identificar os novos registros ingressados na base? É uma abordagem diferente do ano de publicação, pois algumas vezes podem entrar registros antigos que do ponto de vista da base de dados é novo.

Essa demanda é da instância iAHx do Repositorio COVID-WHO mas que entendo que possa ser integrada no produto core.

Relacionado a https://github.com/bireme/db-processing/issues/230

**Comment by renatomurasaki** [comment]
@marcoslmori por favor, configurar ordenamento para utilizar o índice entry_date. Se possível, por favor, deixar esta opção como default.

**Comment by marcoslmori** [comment]
configurado no config.xml

<sort_list>
           <sort>
                   
                <name>YEAR_DESC</name>
               <value>da desc</value>
         </sort>
        <sort>
            <name>RELEVANCE</name>
           <value>weight desc,score desc</value>
         </sort>
         <sort>
                 <name>YEAR_ASC</name>
                <value>da asc</value>
        </sort>
        <sort>
                <name>DATAENTRY_ASC</name>
                <value>entry_date asc</value>
        </sort>
        <sort>
                <name>DATENTRY_DESC</name>
                <value>entry_date desc</value>
        </sort>
</sort_list>

------------------------------------------------
Ajustado label nos idiomas (faltam ar,zh, ru)
DATAENTRY_ASC="Data Entry (increasing)"
DATENTRY_DESC="Data entry (decreasing)"

----------------------------------------------------
erro na opac:
Warning: count(): Parameter must be an array or an object that implements Countable in /home/repository/iahx-opac-git/lib/silex/vendor/twig/twig/lib/Twig/Extension/Core.php on line 1091
No documents match your search terms

**Comment by viniciusandrade** [comment]
Erro retornato pelo Solr: The request sent by the client was syntactically incorrect (can not sort on unindexed field: entry_date)
Estarei realizando ajuste no schema.xml

**Comment by viniciusandrade** [comment]
Ajuste realizado no schema. Solicitei ao @falbrito re-indexação da coleção em teste para validar.

**Comment by viniciusandrade** [comment]
- Re-indexação efetuada e configuração realizada pelo @marcoslmori em ambiente de teste
- Ajuste realizado no ambiente de produção do índice, necessário aguardar restart do server

**Comment by viniciusandrade** [comment]
Implementação em ambiente de produção.
