### ISSUE TITLE
Ajustes para tratamento de caracteres que fazem parte da sintaxe de busca Lucene

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/iahx-opac#17]
Implementar análise da busca na caixa de texto realizada pelo usuário para tomada de decisão se elimina caracteres que fazem parte da sintaxe do Lucene de busca e portanto atualmente  causam comportamento indesejado na busca.

No exemplo abaixo o documento não é recuperado devido a existência dos caracteres **:** e **?** que fazem parte da sintaxe do Lucene e representam respectivamente busca por índice e caracter coringa.  [[sintaxe completa](https://lucene.apache.org/core/2_9_4/queryparsersyntax.html)]

Zika virus: An international emergency?

A proposta é realizar uma  verificação por operadores boolenos **(AND e OR) ou o caracter (** "abre aspas", caso não seja encontrado será aplicado a remoção dos seguintes caracteres dos termos da pesquisa do usuário **? : .**

**Comment by botturam** [comment]
Vinícius,

Houve um efeito colateral nas alterações propostas. Pesquisas com prefixo não retornam ou retornam poucos resultados, a não ser que sejam feitas com operadores booleanos:

tw:rat (retorna 0)
tw:(rat) (retorna resultados)
id:lil-784282 or tw:cat (retorna resultados)

Outra questão, se pesquisarmos:
mh:rat (retorna 1) => mas está errado; foi recuperado no resumo o termo MHRAT no resumo
mh:(rat) (retorna 0) => correto

**Comment by viniciusandrade** [comment]
@botturam 

Retirei o caracter **:** do processo para contornar este efeito colateral. Desta forma no momento só esta retirando os caracteres **?** e **.** da expressão do usuário quando o mesmo não estiver usando operadores booleanos ou o sinal de **(**.
