### ISSUE TITLE
Resultados para termos com hífen e palavras com letras minúsculas e maiúsculas

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/iahx-opac#170]
Inconsistência no número de resultados foram reportados pela Rose ao buscar por termos com as seguintes construções:

SARS-CoV-2
SRAG-CoV-2
2019-nCoV

**Comment by viniciusandrade** [comment]
Para o tipo de campo texto foi alterado ordem de geração das chaves para aplicar primeiro o filtro de **lowercase** e após o filtro de **word delimiter**

Ajuste realizado no schema do índice COVIDOMS.

Exemplo de chaves geradas antes da alteração:
sars | co | v | 2
sarscov | 2

Exemplo de chaves geradas após a alteração:
sars | cov | 2
sarscov | 2

**Comment by viniciusandrade** [comment]
Padrizado parâmetros da geração de chaves entre as etapas de index e query para os campos tipo text (ti, ab, etc).
Ajuste realizado no schema do índice COVIDOMS.
```
org.apache.solr.analysis.WordDelimiterFilterFactory {generateNumberParts=1, catenateWords=1, luceneMatchVersion=LUCENE_36, generateWordParts=1, catenateAll=0, catenateNumbers=1}
```
* Necessário alterar classe BVSStandardAnalyzer para geração de tokens compatíveis com esta alteração

**Comment by renatomurasaki** [comment]
@viniciusandrade fazendo [ti:sars* and not ti:sars-cov-2](https://search.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov/?output=site&lang=en&from=0&sort=&format=summary&count=20&fb=&page=1&skfp=&index=tw&q=ti%3Asars*+and+not+ti%3Asars-cov-2&search_form_submit=)

Repare que sars-cov-2 deveria recuperar o token sars-cov presente em alguns documentos, tais como:

- Potential for developing a SARS-CoV receptor-binding domain (RBD) recombinant protein as a heterologous human vaccine against coronavirus infectious disease (COVID)-19
- Surgical management of head and neck tumours during the SARS-CoV (Covid-19) pandemic
- Searching therapeutic strategy of new coronavirus pneumonia from angiotensin-converting enzyme 2: the target of COVID-19 and SARS-CoV

**Comment by renatomurasaki** [comment]
@viniciusandrade outro comportamento que percebi, na interface do WHO COVID-19, pesquisando no índice de título. Abaixo printscreens para tentar buscar o documento "COVID-19: Current Trends in Invitro Diagnostics"

Não funciona com o texto original do título
![image](https://user-images.githubusercontent.com/1226218/94942953-61b46e00-04ad-11eb-9c7a-a29e63757680.png)

Funciona se retira os dois pontos
![image](https://user-images.githubusercontent.com/1226218/94942986-7264e400-04ad-11eb-8be7-4e5f7db1be88.png)

Não funciona se retira o hífen e mantem os dois pontos
![image](https://user-images.githubusercontent.com/1226218/94943047-84df1d80-04ad-11eb-9c3c-d6a22367af0c.png)

Funciona retirando o hífen e os dois pontos
![image](https://user-images.githubusercontent.com/1226218/94943082-9294a300-04ad-11eb-8dad-f95baba33bf6.png)

**Comment by viniciusandrade** [comment]
@renatomurasaki, infelizmente neste último exemplo não há muito o que se possa fazer uma vez que o sinal de dois pontos **:** faz parte da sintaxe do lucene para indicar busca por determinado índice (ex ti:dengue).  Neste caso a orientação é a busca usando o título entre aspas duplas.

**Comment by renatomurasaki** [comment]
@viniciusandrade entendo, mas aspas duplas só funciona no índice de título e estou percebendo que os usuário tentam isso na opção TW (Title, Abstract, Subject)

**Comment by viniciusandrade** [comment]
@renatomurasaki consegui bons resultados após uma série de tentativas de ajustes na configuração do índice da base covidoms para a busca de termos com hífen (ex: SARS-CoV-2 e COVID-19) no índice TW.

**Resultados antes dos ajustes (índice em produção):**

SARS-CoV-2 (43)
COVID-19 (852)

**Resultados após ajustes (índice em teste):**

SARS-CoV-2 (37.240)
COVID-19 (72.928)

Quando possível, agradeço se puder realizar a comparação da recuperação atual com a disponível neste novo índice que esta disponível em:

https://pesquisa.teste.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov-test/

Obrigado

**Comment by renatomurasaki** [comment]
@viniciusandrade excelente!! Os seguintes testes:

`sars* and not sars-cov-2`

`covid* and not covid-19`

Demonstraram um bom resultado nas alterações que foram feitas. Pode seguir em frente com a atualização.

**Comment by viniciusandrade** [comment]
@renatomurasaki ambiente de produção atualizada.

**Comment by renatomurasaki** [comment]
Funcionando! Obrigado!
