### ISSUE TITLE
Erro ao usar o cluster Year Range no WHO COVID

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/iahx-opac#171]
O erro abaixo ocorre tanto na opção 5 ou 10 anos, como também ao informar o início e fim.

![image](https://user-images.githubusercontent.com/1226218/79463893-ccd9b900-7fcf-11ea-8d02-fa645aeae9ad.png)

**Comment by viniciusandrade** [comment]
Correção efetuada em https://github.com/bireme/iahx-opac/commit/5eede37c5e99f0e8d8323a6316e2fdb83889d756
