### ISSUE TITLE
Inclusão de entry data e DOI no formato RIS

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/iahx-opac#174]

**Comment by viniciusandrade** [comment]
@renatomurasaki 
Para o DOI existe uma tag prevista na documentação do RIS, mas não localizei um específico para entry date, algumas tags citadas no documento seriam:

Y1 | Primary Date
Y2 | Access Date

A lista de campos que eu uso estão nesta página:
https://en.wikipedia.org/wiki/RIS_(file_format)

Quando possível, poderia por favor informar qual tag utilizar?

**Comment by renatomurasaki** [comment]
@viniciusandrade pode implementar o DOI para o formato RIS e deixar suspensa a inclusão do campo entry date, umas vez que ainda não temos esta definição. Semana que vem me reunirei com a equipe de suporte da endnote, juntamente com a equipe da OMS, para tratar desse e outros temas que temos encontrados na exportação completa da base em formato NLM XML.

**Comment by viniciusandrade** [comment]
@renatomurasaki campo DOI adicionado no formato e disponível no ambiente de produção.
Favor re-abrir quando for definido o tag para o entry date.

**Comment by renatomurasaki** [comment]
@viniciusandrade o DOI sumiu do formato RIS (campo DO). No XML é o campo AID

**Comment by viniciusandrade** [comment]
@renatomurasaki foi alterado o elemento de DOI para AID no schema do índice. Ajuste realizado no template RIS e atualizado em produção.

**Comment by renatomurasaki** [comment]
Testado e funcionando. Obrigado
