### ISSUE TITLE
Inclusão de DOI no formato CSV

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/iahx-opac#175]

**Comment by viniciusandrade** [comment]
@falbrito / @botturam 
Não localizei este campo disponível na resposta do Solr, lembrando que ele precisa estar definido no **schema** como **stored=true** ... poderiam por favor verificar e me retornar quando o campo estiver OK?

**Comment by botturam** [comment]
Vinicius, por favor, tente agora. Inseri o campo "doi" no schema.xml

**Comment by botturam** [comment]
disponível em instância de "teste".

**Comment by viniciusandrade** [comment]
Marcelo, agora esta OK.  Favor informar quando o ajuste estiver disponível em produção.

Campo adicionado ao formato de exportação CSV em teste.

**Comment by botturam** [comment]
Em produção, às 15:00 será a próxima virada.

**Comment by viniciusandrade** [comment]
:+1:

**Comment by viniciusandrade** [comment]
Ajuste em produção.

**Comment by renatomurasaki** [comment]
@viniciusandrade o DOI desapareceu do CSV. Aconteceu o mesmo no formato RIS. Tenho a sensação que o nome do elemento XML mudou. Hoje está em AID e creio que no passado era DOI.

**Comment by viniciusandrade** [comment]
@renatomurasaki templates RIS e CSV alterados para elemento AID.
Ajuste em produção.

**Comment by renatomurasaki** [comment]
Testado e funcionando. Obrigado!
