### ISSUE TITLE
Verificar o link do cluster Journal, do ambiente de teste do WHO COVID, quando o nome da revista é composta por caracteres chineses

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/iahx-opac#178]
Identificado com o @viniciusandrade que o valor passado pelo javascript não está incorporando o nome com caracteres chineses.

Por exemplo, o link para a revista BMJ tem o link:
`javascript: add_filter('ta_cluster_bmj');`

Já todas as revistas com caracteres chineses tem o seguinte link:
`javascript: add_filter('ta_cluster_');`

Por isso que ao clicar em qualquer nome de revista em chinês, sempre recupera a primeira ocorrência da lista.

![image](https://user-images.githubusercontent.com/1226218/80533732-7cba0980-8974-11ea-82b0-934d37ebadf8.png)

**Comment by viniciusandrade** [comment]
@renatomurasaki / @falbrito / @botturam 

Subi para o ambiente de testes uma modificação no template responsável em montar a coluna de filtros para tratar este issue.  

A ideia é monitorar para verificar se esta alteração terá efeito colateral em algum outro ponto do sistema, vamos usando e se alguém notar algum comportamento errado no uso dos filtros favor informar por arqui.

Obrigado.

**Comment by renatomurasaki** [comment]
@viniciusandrade aparentemente a recuperação pelo periódico com escrita chinesa agora está funcionando corretamente!!
