### ISSUE TITLE
Quantidade mostrada no cluster difere da quantidade do resultado de busca

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/iahx-opac#179]
Reproduzi esse problema apenas no cluster de Assunto Principal, tanto na interface de produção como nas duas de teste da base do WHO COVID-19.

Reparem nas imagens abaixo. O cluster mostra 1.493 documentos para o Assunto Principal "Coronavirus Infections" e 1.649 documentos recuperados.

![image](https://user-images.githubusercontent.com/1226218/80756985-d1db5400-8b09-11ea-8ff0-85c54df0a8a0.png)

**Comment by viniciusandrade** [comment]
Na configuração da interface o cluster de assunto principal estava apontando para o cluster de assunto geral.
Realizado ajuste no config.xml da interface e nos arquivos de tradução.

**Comment by renatomurasaki** [comment]
@marcoslmori veja esse issue, por favor, pois era um problema de configuração do OPAC.
