### ISSUE TITLE
Pesquisa Avançada utilizando operador "OR" aparece resultado "AND"

### ISSUE THREAD

**Issue by alvesmarilda** [bireme/iahx-opac#180]
Colegas,

Recebemos uma mensagem de usuário no Feedback reportando o erro abaixo:

 "Ao usar a pesquisa avançada, quando selecionamos dois assuntos separados por OR (na caixa de seleção do operador) ao clicar em pesquisar, a tela de resposta de artigos encontrados dá a resposta usando o AND. O erro pode ser constatado comparando: - os totais finais, um pesquisa de 2 itens com OR deve dar o mesmo valor ou maior do que uma das pesquisas sozinhas, e dá menor. - outra forma de perceber a falha, é que a query final mostrada na barra superior troca o OR pelo AND. Se digitar a query completa na lupa e pesquisar, dá certo. Mas muitos não sabe fazer isso e usam os campos da pesquisa avançada."

Obrigada!

**Comment by renatomurasaki** [comment]
Assunto sendo tratado no issue #211
