### ISSUE TITLE
Inserir Guia Rápido Covid-19

### ISSUE THREAD

**Issue by marcioalvessilva** [bireme/iahx-opac#181]
Inserir botão de ajuda com link para o Guia Rápido Covid-19 nos idiomas (pt, es, en, fr, zh), demais idiomas (ru e ar) com link para versão em inglês. 

Grato!

**Comment by viniciusandrade** [comment]
@marcioalvessilva,

Botão de ajuda adicionado e guias transferidos para o servidor. 

Favor verificar e informar se esta tudo correto. Obrigado.

**Comment by marcioalvessilva** [comment]
Grato @viniciusandrade!
