### ISSUE TITLE
Ajuste de contraste na página inicial

### ISSUE THREAD

**Issue by marcioalvessilva** [bireme/iahx-opac#183]
Boa tarde Vinicius!
Por favor inserir css ".bodyBlack .alert-light, .bodyBlack .box5" no arquivo acessibilidade.css
pode ser junto a linha 37.

exemplo como deve ficar:. bodyBlack .page-link, .bodyBlack .titleArt, **.bodyBlack .boxEvidence, .bodyBlack .alert-light, .bodyBlack .box5**

Resultado desejado:
![image](https://user-images.githubusercontent.com/48724136/83158556-4ab6d700-a0db-11ea-88c6-96b0d7b3f86d.png)

**Comment by viniciusandrade** [comment]
Ajuste realizado. Obrigado por informar.
