### ISSUE TITLE
Mudança de URL nos formatos RSS e XML

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/iahx-opac#184]
Está aumentando a demanda por coleta de dados nas interfaces iAHx, principalmente na WHO COVID-19 e GIM. Ainda é preciso avaliar os logs do apache para ter a real dimensão deste uso, entretanto há 3 casos de uso nos últimos 2 meses neste sentido.

O que ocorre é que com a coleta, os sistemas externos que estão utilizando os metadados não estão gerando hits para estas interfaces, pois o campo <arr name="ur"> aponta para o texto completo e não para o registro bibliográfico na nossa interface. Quando o texto completo não está disponível, este campo está ausente.

**Comment by viniciusandrade** [comment]
Revisado:

- O template que monta o RSS já esta indicando a URL da pesquisa iAHx.

- Para o formato XML se trata do retorno que vem direto da API Solr com os elementos do índice e atualmente não existe um template na camada do iAHx para realizar este tratamento.

**Comment by renatomurasaki** [comment]
@viniciusandrade está ok o XML manter o link para o texto completo, conforme haviamos conversado antes, pois é o melhor para o usuário final. RSS é mais usado para integração de conteúdo entre sites ou leitor e assim faz mas sentido levar o usuário até o iAHx.

**Comment by viniciusandrade** [comment]
:+1:
