### ISSUE TITLE
Comportamento do botão "Filtrar" na página dos clusters quando o usuário não informa expressão de busca

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/iahx-opac#185]
Ao clicar no botão filtrar o browser não mostra que está carregando e como há uma demora para devolver o resultado de busca, parece que não está funcionando o botão. Seria possível atualizar o texto do botão para aparecer o ícone de carregando?

**Comment by viniciusandrade** [comment]
Implementado indicador de carregamento. 

Relacionado ao issue #186
