### ISSUE TITLE
Comportamento do botão "Aplicar" qdo o usuário seleciona a opção "Mais filtros"

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/iahx-opac#186]
Ao clicar no botão Aplicar o browser não mostra que está carregando e como há uma demora para devolver o resultado de busca, parece que não está funcionando o botão. Seria possível atualizar o texto do botão para aparecer o ícone de carregando?

**Comment by viniciusandrade** [comment]
@renatomurasaki, como existem outros momentos do sistema com delay para o processamento das requisições acho que seria mais interessante tentar mostrar uma imagem de loading geral para todos os submits.

@marcioalvessilva, seria possível propor no mockup um div de loading para ser mostrado sempre que um form é enviado? Exemplo (https://www.worldcat.org/) 

Obrigado.

**Comment by viniciusandrade** [comment]
@renatomurasaki,

O @marcioalvessilva fez uma proposta de imagem de loading que implementei para todo o processo de submit de form do iAHx, de forma a sempre indicar ao usuário que o sistema esta processando sua requisição.

Quando possível, favor avaliar no ambiente de testes (https://pesquisa.teste.bvsalud.org/portal/) realizando um shift+refresh para carregar a mudança de javascript realizada.

Obrigado

**Comment by renatomurasaki** [comment]
Ficou muito bom! O uso dos losangos foi uma excelente decisão!
Seria possível ter o mesmo comportamento ao clicar no breadcrumb?

**Comment by viniciusandrade** [comment]
@renatomurasaki,
Sim, comportamento adicionado ao clicar no breadcrumb.

**Comment by renatomurasaki** [comment]
Obrigado, Vini! Está excelente. Pode colocar em produção.

**Comment by viniciusandrade** [comment]
Ajuste em produção.
