### ISSUE TITLE
Realizar tradução dos labels do cluster Tipo de Estudo

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/iahx-opac#187]
@marcoslmori por favor, realize a tradução dos labels que apareceram no cluster Tipo de Estudo da interface iAHx do WHO COVID-19, como se vê na imagem abaixo

![image](https://user-images.githubusercontent.com/1226218/84810502-cec8f400-afe1-11ea-94b0-55d38bb8c5c0.png)

Acho que o @botturam tem os nomes por extenso.

**Comment by renatomurasaki** [comment]
@marcoslmori por favor, verificar este issue

**Comment by botturam** [comment]
labels traduzidos. Disponíveis em produção.
