### ISSUE TITLE
Possível perda do ducentésimo registro durante processo de exportação em formato RIS ou CSV

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/iahx-opac#188]
@viniciusandrade não consegui reproduzir. Detalhes estão no email "WHO Database: Records Missing  / incomplete Entry Dates" enviado pela OMS Genebra.

**Comment by viniciusandrade** [comment]
@renatomurasaki código revisado para exportação em formato RIS e CSV.

Por favor, quando possível, solicitar a validação pela equipe da OMS.

Obrigado

**Comment by renatomurasaki** [comment]
@viniciusandrade done e aguardando feedback

**Comment by viniciusandrade** [comment]
:+1:

**Comment by renatomurasaki** [comment]
O suporte do Endnote encontrou o seguinte erro

![image](https://user-images.githubusercontent.com/1226218/87724687-40878f80-c792-11ea-9f82-0f92c5cbafe4.png)

> The issue is 221 time in the file you have ER  -TY
> The carriage return was missing so those references did not import which is why we would get only 44062 references imported.

**Comment by renatomurasaki** [comment]
@viniciusandrade o Tomas da WHO confirmou o seguinte

> There is definitely a pattern also with the missing citation. It is every 200th occurrence that ends up missing the carriage return and having the ER  -TY which needs to “Find and Replaced” to do a complete full download.

**Comment by viniciusandrade** [comment]
@renatomurasaki subi uma nova versão do código de exportação para a produção.

Agradeço, quando possível, solicitar novo teste.

Obrigado

**Comment by renatomurasaki** [comment]
Teste solicitado e aguardando feedback

**Comment by renatomurasaki** [comment]
@viniciusandrade parabéns pelo empenho em encontrar a causa do erro. De acordo com a equipe do CDC/USA, o problema foi solucionado! Obrigado!

**Comment by viniciusandrade** [comment]
:+1:
