### ISSUE TITLE
Criar área de disclaimer quando o documento visualizado é um preprint

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/iahx-opac#190]
Esta área de disclaimer deve aparecer na visualização dos metadados do documento (página de detalhes), quando o mesmo for do tipo preprint.

@marcioalvessilva por favor, proponha uma solução para este caso, juntamente com o @viniciusandrade 

Os textos nos 4 idiomas estão disponíveis no arquivo anexo

[Disclaimer preprints 4 idiomas.docx](https://github.com/bireme/iahx-opac/files/4851844/Disclaimer.preprints.4.idiomas.docx)

**Comment by marcioalvessilva** [comment]
Conforme solicitado segue link de sugestão para apresentar texto de preprint, aguardo aprovação.
http://mockups.teste.bireme.org/iahx/interna.php

**Comment by viniciusandrade** [comment]
@marcioalvessilva obrigado.

@renatomurasaki ajustes  aplicados na interface.

Exemplo:
https://pesquisa.bvsalud.org/portal/resource/en/pps-750

**Comment by renatomurasaki** [comment]
Perfeito

**Comment by renatomurasaki** [comment]
Obrigado, @viniciusandrade e @marcioalvessilva
