### ISSUE TITLE
Caixa de pesquisa não mostra a estratégia aplicada

### ISSUE THREAD

**Issue by alvesmarilda** [bireme/iahx-opac#191]
Vinicius,

Recebemos feedback de Usuário informando que a caixa de pesquisa fica em branco após a estratégia aplicada.

Abaixo segue um exemplo:

Teste de busca com vários filtros e realmente a caixa de pesquisa não mostra a estratégia aplicada.

https://pesquisa.bvsalud.org/portal/?output=&lang=pt&from=&sort=&format=&count=&fb=&page=1&filter%5Bdb%5D%5B%5D=LILACS&filter%5Btype_of_study%5D%5B%5D=case_reports&skfp=true&index=tw&q=&filter%5Bmh%5D%5B%5D=Alimenta%C3%A7%C3%A3o+Artificial

![image](https://user-images.githubusercontent.com/38661168/86243853-6c452b80-bb7d-11ea-9e8d-6dc00d8fb690.png)

Obrigada

**Comment by viniciusandrade** [comment]
@alvesmarilda 
Ajuste realizado. Favor, quando possível, verificar e informar usuário caso OK.

Obrigado.

**Comment by viniciusandrade** [comment]
Marilda reportou por email que o ajuste esta OK.
