### ISSUE TITLE
Exportação de registros formato RIS e CSV

### ISSUE THREAD

**Issue by pintoros** [bireme/iahx-opac#192]
Solicito o ajuste indicado para o serviço de exportação disponível no iAHx , conforme explicado no documento anexo, com objetivo de corrigir erro na exportação de registros nos formatos RIS e CSV.
[Exportacao_RIS.pdf](https://github.com/bireme/iahx-opac/files/4860168/Exportacao_RIS.pdf)

**Comment by renatomurasaki** [comment]
@viniciusandrade este issue e a explicação dada pelo pessoal da Fiocruz, no PDF anexo, também deve resolver o problema encontrado em 26/jun pelo Tomas, como se descreve abaixo

- **I have tried to analyze the RIS file and while I can find 35146 (ER - )  End record (which is good)  I can only find 35109 (TY -) indication type of record, (which is not good)  so when imported at least 37 records don’t have this thus they “get lost” bunched into another record I guess Also strange that double 37 is 74 (coincidence).**

**Comment by viniciusandrade** [comment]
Ajuste realizado para exportar por padrão a tag **TY**  como  **GEN** caso não seja possível mapear o tipo de registro com os tipos do formado RIS.

@pintoros,
Agradeço, quando possível, validar se esta OK.

Obrigado
Vinicius

**Comment by renatomurasaki** [comment]
Encerrando chamado com os testes realizados no âmbito do WHO COVID
