### ISSUE TITLE
Proposta de mockup para mostrar dados de autor e afiliação na página de detalhamento dos documentos

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/iahx-opac#193]
Márcio, por favor, poderia propor um mockup para mostrarmos as afiliações dos autores na página de detalhamento dos documentos no iAHx?

Benchmarking:
1 - http://journal03.magtech.org.cn/Jweb_sdykdxxb/CN/10.3969/j.issn.1006-7795.2020.02.023
![image](https://user-images.githubusercontent.com/1226218/86937342-82bb2c00-c115-11ea-8563-88a1ee1ad4ea.png)

2 - https://pubmed.ncbi.nlm.nih.gov/32500409/
![image](https://user-images.githubusercontent.com/1226218/86937769-05dc8200-c116-11ea-9613-d9800ce7e943.png)

Hoje temos a possibilidade de replicar os dados de autor e a respectiva afiliação, tendo em vista a disponibilidade da seguinte informação no XML do documento:

```
<arr name="afiliacao_autor">
<str>Procianoy, Renato Soibelmann; Universidade Federal do Rio Grande do Sul, Porto Alegre. Hospital de Clinicas de Porto Alegre. Porto Alegre. BR</str>
<str>Silveira, Rita C; Universidade Federal do Rio Grande do Sul. Hospital de Clinicas de Porto Alegre. Porto Alegre. BR</str>
<str>Manzoni, Paolo; University Hospital Degli Infermi. Department of Maternal-Infant Medicine. IN</str>
<str>Sant´Anna, Guilherme; McGill University Health Center. Montreal. CA</str>
</arr>
```

**Comment by marcioalvessilva** [comment]
Bom dia!
@renatomurasaki  e @viniciusandrade 
Fiz uma versão para afiliações, segue link do mockup, aguardo feedback.
http://mockups.teste.bireme.org/iahx/interna.php.

Grato!

**Comment by renatomurasaki** [comment]
@marcioalvessilva obrigado! Eu acho que não conseguimos atualmente fazer um de-para dessa maneira entre autor e afiliação, correto @viniciusandrade? Acho que bastaria a seta para baixo (talvez com um pouco mais de destaque) e a repetição abaixo de nome do autor e informação de afiliação. O que acha @viniciusandrade ?

**Comment by viniciusandrade** [comment]
@renatomurasaki pelos exemplos que verifiquei bate a sequência dos elementos do autor com a sequência dos elementos de afiliação ... mas acho improvável que essa regra seja 100%.

@botturam poderia confirmar se existem casos em que a sequência dos autores nos elementos **au** e **afiliacao_autor** são diferentes ou se existem autores que podem não ter informação de afiliação?

**Comment by renatomurasaki** [comment]
@viniciusandrade pode ter um autor no meio dos demais sem afiliação, o que "quebraria" o alinhamento dos elementos.

**Comment by viniciusandrade** [comment]
@renatomurasaki,  favor validar box de afiliação dos autores disponível no ambiente de testes:

https://pesquisa.teste.bvsalud.org/portal/resource/pt/mdl-29953935

Obrigado

**Comment by renatomurasaki** [comment]
@viniciusandrade excelente! Assim que tiver na produção me avise para divulgar. Obrigado

**Comment by viniciusandrade** [comment]
@renatomurasaki, ajuste disponível em produção :+1: 

https://pesquisa.bvsalud.org/portal/resource/pt/mdl-29953935
