### ISSUE TITLE
Ajustes no cluster para mostrar Preprints

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/iahx-opac#194]
Pessoal, já está disponível na interface o disclaimer para preprints

https://pesquisa.bvsalud.org/portal/resource/en/pps-750

Precisamos configurar os clusters "Coleção" e "Base de dados" da seguinte maneira:

Coleção = Preprints
Base de dados = SciELO Preprints

O nome da base atual está PREPRINT-SCIELO, por favor, ajustar a tradução do label para SciELO Preprints

Os novos repositórios de preprints que forem entrando devem seguir esta mesma lógica:

Para documentos preprints Fiocruz:

Coleção = Preprints
Base de dados = Fiocruz Preprints

Para EmeRI

Coleção = Preprints
Base de dados = IBICT Preprints (EmeRI)

**Comment by botturam** [comment]
Inseridas novas entradas em pps_regional.xml:

<field name="db">PREPRINT-SCIELO</field>
<field name="collection">09-preprints</field>

6f estará disponível.

**Comment by marcoslmori** [comment]
> Base de dados = SciELO Preprints

Tradução no cluster bases de dados feito em instancia de teste.  Na sexta-feira tradução do collection

**Comment by marcoslmori** [comment]
deixado preparado o cluster collection para sexta-feira

**Comment by botturam** [comment]
já pode atualizar em produçao. Ambiente de teste OK.

**Comment by marcoslmori** [comment]
Atualizado em produção!!

**Comment by anakatiacamilo** [comment]
Bom dia @marcoslmori, poderia traduzir a Base de dados Fiocruz Preprints também já esta em produção.  

<field name="db">PREPRINT-FIOCRUZ</field>
Base de dados = Fiocruz Preprints

Grata

**Comment by marcoslmori** [comment]
Ok, katinha!

**Comment by marcoslmori** [comment]
atualizado na instancia de teste do portal.  Por favor, validar para colocar em produção  https://pesquisa.teste.bvsalud.org/portal

**Comment by renatomurasaki** [comment]
@marcoslmori está perfeito! Obrigado

**Comment by marcoslmori** [comment]
em produção.

**Comment by anakatiacamilo** [comment]
@marcoslmori  Obrigada!!
