### ISSUE TITLE
Substituir o link do rodapé do IAHx "enviar um comentário /comunicar um erro" para o novo serviço de feedback do usuário

### ISSUE THREAD

**Issue by marcoslmori** [bireme/iahx-opac#196]
Por favor, 

Substituir o link do rodapé do IAHx "enviar um comentário /comunicar um erro" para o novo serviço de contato da BIREME baseado no Livezilla

----------------------------------------------
PT- https://bvsalud.org/contate-nos/
ES- https://bvsalud.org/es/contactenos/
EN- https://bvsalud.org/en/contact_us/
---------------------------------------------

e precisa incluir o rótulo  "Solicitar ajuda"

conforme exemplo abaixo: 

Solicitar ajuda / Enviar comentário / Comunicar erro
Solicitar ayuda / Enviar comentario / Reportar un error
Ask for help / Leave a comment / Report an error
Demander de l'aide/ Laisser un commentaire /Signaler une erreur

Obrigado,

**Comment by viniciusandrade** [comment]
@marcoslmori,
 
Link substituído no repositório do IAHX para o novo template. 

Ajustes no texto realizado no **texts.ini** da instância portal.

Caso necessário, favor realizar o ajuste no rótulo para outras instâncias.

Obrigado
