### ISSUE TITLE
Alterar a tradução do label resumo em chinês

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/iahx-opac#199]
A grafia correta é 摘要

Label revisado pela equipe chinesa que colabora com a base WHO COVID-19.

**Comment by marcoslmori** [comment]
OK

**Comment by marcoslmori** [comment]
Ajustado na instancia de teste e solicitado ao ITI para colocar em produção. Chamado 7313

**Comment by marcoslmori** [comment]
sincronizado em produção. validar.

**Comment by renatomurasaki** [comment]
Parece ok!
