### ISSUE TITLE
Inclusão do DOI no formato de apresentação do iAHx Regional (Portal Regional da BVS)

### ISSUE THREAD

**Issue by suelisuga** [bireme/iahx-opac#200]
@botturam e @falbrito ,

Em continuidade ao fluxo de ações necessárias à inclusão do DOI presente nos registros bibliográficos, solicito apresentação da informação presente no campo Número do DOI [724] no portal regional da BVS.

Conforme combinado com @pintoros , ela deve indicar o local e formato da apresentação.

O preenchimento do campo é alfanumérico, ou seja, um exemplo: 10.1590/S0102-311X2008000500013 

Muito obrigada!

**Comment by botturam** [comment]
Inseridos 2 campos no processamento do Portal-regional (e Brasil, Hanseníase, Homeopatia, etc.)

1) pesquisa orcid e wosid:
<field name="**auid**"                       type="string"                   indexed="true"   stored="true"   multiValued="true" />

2) pesquisa doi:
<field name="**aid**"                         type="string"                   indexed="true"   stored="true" />

**Comment by botturam** [comment]
em processamento...

**Comment by botturam** [comment]
disponível em produção:

Ex:
    <field name="aid">10.20396/bjos.v19i0.8657508</field>
    <field name="auid">0000-0003-0486-8512</field>
