### ISSUE TITLE
Apresentação do número persistente do autor pessoal (ORCID ou ResearcherID) no portal regional da BVS (iAHx Regional)

### ISSUE THREAD

**Issue by suelisuga** [bireme/iahx-opac#201]
@botturam e @falbrito ,

Solicito apresentação do número persistente do autor pessoal presente nos registros bibliográficos do FI-Admin no portal regional da BVS (iAHx Regional).

A informação estará presente nos atributos:
k => Orcid
s => Web of Science ResearcherID

Nos registros de nível:
Série - campo [10] Autor pessoal
Monográfico - campo [16]  Autor pessoal
Coleção - campo [23] Autor pessoal

Local e forma de apresentação será indicada por @pintoros 

Muito obrigada
Sueli

**Comment by botturam** [comment]
olhar chamado 343:

https://github.com/bireme/db-processing/issues/343

**Comment by suelisuga** [comment]
muito obrigada @botturam e @falbrito !
