### ISSUE TITLE
Inclusão de índice para recuperação de Identificação de Artigo (DOI)

### ISSUE THREAD

**Issue by pintoros** [bireme/iahx-opac#203]
Solicito a criação do índice para recuperação no iAHx , baseado no subcampo Article_identifier, referente ao chamado #200.
Sugestão da tag: aid

![AID](https://user-images.githubusercontent.com/29313904/90057129-56677200-dcb6-11ea-8631-ca54d8fde1f3.PNG)

**Comment by suelisuga** [comment]
@pintoros Rose,

Sim, muito obrigada! 
Penso que o prefixo **aid** é melhor que doi visto que outros identificadores podem ser incluidos com esse mesmo objetivo.

Abraços

**Comment by botturam** [comment]
Disponível em produção:

Ex:
<field name="aid">10.20396/bjos.v19i0.8657508</field>
<field name="auid">0000-0003-0486-8512</field>

pesquisa na IAHx:
aid:"10.20396/bjos.v19i0.8657508"
auid:"0000-0003-0486-8512"

**Comment by suelisuga** [comment]
muito obrigada @botturam, @falbrito e @pintoros !
