### ISSUE TITLE
A exportação nos formatos RIS e CSV não funcionam quando há somente um registro selecionado

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/iahx-opac#209]
Quando a exportação é solicitada com apenas um registro selecionado, o arquivo exportado é vazio.

**Comment by renatomurasaki** [comment]
Problema encontrado por usuário do iAHx WHO COVID-19

**Comment by viniciusandrade** [comment]
@renatomurasaki, ajuste realizado e atualizado em produção. 

Favor, quando possível informar usuário. Obrigado.
