### ISSUE TITLE
Pesquisa avançada - Erro operadores booleanos entre as linhas

### ISSUE THREAD

**Issue by pintoros** [bireme/iahx-opac#211]
O operador booleano AND não muda no resultado quando alterado para OR ou AND NOT. Ver na imagem, foi utilizado OR, mas no resultado permaneceu AND.
![image](https://user-images.githubusercontent.com/29313904/94086829-7c6a5100-fde2-11ea-8c40-8b5a7994356d.png)
![image](https://user-images.githubusercontent.com/29313904/94086892-ad4a8600-fde2-11ea-9790-f0fda5002cfe.png)

**Comment by pintoros** [comment]
Esse erro já foi reportado nos issues 120 e 180. Desde 2017!

**Comment by renatomurasaki** [comment]
Duplicado de #120 e #180

**Comment by viniciusandrade** [comment]
@pintoros,
Correção aplicada na busca avançada, favor quando possível validar.

Obrigado.

**Comment by pintoros** [comment]
Validado! Erro não ocorre mais.
