### ISSUE TITLE
Pesquisa avançada - Excesso de parênteses e tw: defoult

### ISSUE THREAD

**Issue by pintoros** [bireme/iahx-opac#212]
Cada linha do formulário deve contar com apenas 1 par de parênteses e NÃO incluir tw:  a frente do mesmo pois poderá anular outro índice aplicado pelo usuário, por exemplo mh:
![image](https://user-images.githubusercontent.com/29313904/94087113-53968b80-fde3-11ea-8d86-f77dd7201e10.png)
![image](https://user-images.githubusercontent.com/29313904/94089742-4fba3780-fdea-11ea-9e43-267a7e8e923d.png)

**Comment by viniciusandrade** [comment]
@pintoros,

Pelo que pude observar esse comportamento esta provavelmente relacionado com a barra de pesquisa onde sempre esta selecionado a opção **Título, resumo, assunto** fazendo com que o sistema sempre coloque o **TW:** para qualquer expressão informada pelo usuário pois esta implicito que ele selecionou a opção da caixa conforme imagem abaixo:
![barra-busca](https://user-images.githubusercontent.com/349287/95260072-7fac0680-07fe-11eb-83c8-16e762bd065a.png)

ficando:
**tw:(ti:malaria)**

O que podemos tentar é tirar o valor **TW** da caixa de seleção e com isso todas as expressões vão ficar sem o prefixo **tw:** na construção da expressão de busca, eu vi rapidamente que o Pubmed aparentemente não coloca nenhum prefixo deixando a query limpa. No nosso caso preciso da sua avaliação para saber quais os impactos desta alteração.

Deixei o ambiente de testes configurado para não usar prefixo na opção **Título, resumo, assunto** e quando possível agradeço você realizar a avaliação necessária desta alteração. 

https://pesquisa.teste.bvsalud.org/portal/

Obrigado

**Comment by pintoros** [comment]
@viniciusandrade fiz a avaliação na instância de teste e notei que não há impacto no resultado da pesquisa ao retirar o TW do prefixo das estratégias na caixa de busca avançada, assim como o excesso de parênteses. 
Pode, por favor, confirmar essa alteração.

Obrigada

**Comment by viniciusandrade** [comment]
@pintoros OK, ajuste aplicado em produção ... lembrando que esta alteração afeta também a caixa de busca simples uma vez que o prefixo foi retirado na configuração. Qualquer efeito não desejado notado favor re-abrir este issue.
