### ISSUE TITLE
em iahx-covidoms, colocar o cluster "collection" na mesma ordem que em iahx-portal-regional

### ISSUE THREAD

**Issue by botturam** [bireme/iahx-opac#217]
alterada a ordem do cluster "collection" em serverofi5:/home/javaapps/iahx-server/indexes/covidoms/main/conf/solrconfig.xml

disponível em teste:
https://pesquisa.teste.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov/

**Comment by renatomurasaki** [comment]
Obrigado, Marcelo! Deixar somente os registros WHO COVID-19 como "Databases of international organizations". As demais, com exceção de Preprints, ficam como "International databases"

**Comment by botturam** [comment]
Faltava apenas configurar a linha de coletasXML.tab, coluna 01-international:

czh regional|CNKI_Lanzhou||s|n||01-internacional|UTF-8|czh.lil|bvs.reg|covidwho

Aguardar o próximo processamento

**Comment by botturam** [comment]
disponível em produção.
