### ISSUE TITLE
NOT ao invés de AND NOT na caixa detalhe da pesquisa

### ISSUE THREAD

**Issue by pintoros** [bireme/iahx-opac#219]
Ao selecionar o operador AND NOT ou digitá-lo na linha da caixa de busca na modalidade avançada, a grafia aparece correta na caixa de busca, porém na caixa DETALHE DA PESQUISA aparece somente como NOT. O operador NOT não é reconhecido na BVS causando erro na busca para quem utiliza a expressão da caixa DETALHE DA PESQUISA para editar a busca ou guardar o histórico.
![image](https://user-images.githubusercontent.com/29313904/95779771-03537080-0ca1-11eb-8841-15c6b0821cbf.png)

**Comment by viniciusandrade** [comment]
@pintoros ajuste disponível no ambiente de testes, favor quando possível validar.

Obrigado

**Comment by pintoros** [comment]
Validado Vinícius!

Obrigada
