### ISSUE TITLE
Comportamento incorreto nos links dos idiomas 

### ISSUE THREAD

**Issue by marcoslmori** [bireme/iahx-opac#223]
Recebido via ocomon  a seguinte solicitação - chamado 7289
--------------------------------------------------
Solicito ajustar o redirecionamento das seguintes páginas:

Navegação nos idiomas:
Link para interfaces de idiomas Decs vai para pagina de pesquisa ao invés de mudar a interface de acordo com o idioma escolhido - https://pesquisa.bvsalud.org/portal/decs-locator/?lang=pt

Link para interface de idiomas Busca avançada vai para pagina de pesquisa ao invés de mudar a interface de acordo com o idioma escolhido - https://pesquisa.bvsalud.org/portal/advanced/?lang=pt

**Comment by viniciusandrade** [comment]
Resolvido em https://github.com/bireme/iahx-opac/commit/99f2f62aa8c3ac7f61d367ee7d9b1c363451a22d
