### ISSUE TITLE
Link de texto completo não funciona

### ISSUE THREAD

**Issue by marcoslmori** [bireme/iahx-opac#227]
Usuário via livezilla, reclama que o link de texto completo está habilitado mas ao clicar o link não funciona. 

https://pesquisa.bvsalud.org/portal/resource/pt/mdl-30137119

**Comment by viniciusandrade** [comment]
@marcioalvessilva a duplicação do código da coluna da direita da página de resultados para mobile teve um pequeno efeito colateral quando o registro possue mais de um link para o texto completo ... nestes casos o link abria um div abaixo contendo a lista para o usuário visualizar os diferentes links do texto completo. 

Como esta div usa o atributo ID acredito que com a duplicação do código este ID passou a não ser mais único na página ... poderia, quando possível dar uma olhada como podemos tratar esta condição.

Obrigado

**Comment by viniciusandrade** [comment]
@marcoslmori correção realizada com o apoio do @marcioalvessilva favor verificar se esta OK e informar a usuária.

**Comment by marcoslmori** [comment]
validado e informado ao usuário
