### ISSUE TITLE
Upload date of each article to your database

### ISSUE THREAD

**Issue by marcoslmori** [bireme/iahx-opac#228]
Suggestion received from the livezilla system - ticket 12166
-------------------------------
Could you please add the upload date of each article to your database? It would be better if you can build a function for people to search/filter the articles by date. The current function of filtering by year is not quite useful for COVID articles. Alternatively, a daily or weekly downloadable file of new articles might also help. Thanks.

**Comment by renatomurasaki** [comment]
Isso já existe. Basta utilizar a expressão `entry_date:YYYYMMDD`. É a data de entrada do registro na base de dados

**Comment by renatomurasaki** [comment]
@marcoslmori favor informar o usuário
