### ISSUE TITLE
Criar mecanismo que permita a exportação de faixas dos registros em formato XML

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/iahx-opac#231]
O usuário poderá informar os parâmetros de início (from) e total a ser exportado  (count) além de poder usar o parâmetro de query (q) para filtrar os registros a serem exportado.

Conforme definido em reunião 09/11/20 o formato XML a ser utilizado é formato disponibilizado pelo Solr (raw) contendo todos os campos armazenados (stored=true) do índice.

**Comment by renatomurasaki** [comment]
@viniciusandrade XML já temos, ou está pensando em algo diferente?

**Comment by viniciusandrade** [comment]
@renatomurasaki sim temos.  Este issue esta relacionado a criação de mecanismo que permita a exportação dos registros em ranges conforme discutimos.

**Comment by renatomurasaki** [comment]
@viniciusandrade mas hoje já temos a possibilidade de usar os parâmetros `count` e `from` 

https://pesquisa.bvsalud.org/portal/?output=xml&lang=pt&from=0&sort=&format=summary&count=20&fb=&page=1&filter%5Bdb%5D%5B%5D=LILACS&skfp=true&index=&q=

**Comment by viniciusandrade** [comment]
@renatomurasaki puxa é verdade ... não lembrava que era possível usar os parâmetros **count** e **from** via url ... pensei que estava restrito ao parâmetro page. 

Também fiz o teste trocando o **output=xml** para **output=csv** e **output=ris** e aparentemente também funcionou para estes casos ... desta forma o que discutimos ontem que o usuário não conseguia realizar a exportação de uma quantidade grande de registros nestes 3 formatos não é realidade certo? Bastaria ter uma página de ajuda explicando o uso destes parâmetros?

**Comment by renatomurasaki** [comment]
@viniciusandrade que surpresa boa! Isso demonstra boa arquitetura da solução! Não ousei mudar o parâmetro para ver se funcionava com CSV e RIS.

Hoje o comportamento é baixar direto o arquivo RIS ou CSV. Será que deveria ter um parâmetro para decidir quando faz download ou quando realiza o streaming/leitura rest?

**Comment by renatomurasaki** [comment]
@viniciusandrade também é importante considerar o nosso SLA no âmbito da quantidade máxima de registros a serem recuperados por lote, tendo um limite máximo para o parâmetro count.

**Comment by viniciusandrade** [comment]
@renatomurasaki, certo acho que seria importante o usuário poder realizar a coleta sem ter que baixar os arquivos. 

Assim que eu documentar estes parâmetros na wiki aqui do projeto vou fechar estes issues realacionado a exportação em faxias e crio outros issues para a questão do streaming e quantidade máxima de registros recuperados por lote.

**Comment by renatomurasaki** [comment]
@viniciusandrade ok! Mas deixe parametrizado para decidir fazer download ou o streaming, ok? Há caso de uso para ambos.

**Comment by viniciusandrade** [comment]
:+1:

**Comment by viniciusandrade** [comment]
Mecanismo existente no core do IAHX documentado em: https://github.com/bireme/iahx-opac/wiki/API
