### ISSUE TITLE
Ao tentar remover um filtro, logo após ter aplicado os passos do EVID@Easy, a interface volta para a visualização padrão

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/iahx-opac#244]
![image](https://user-images.githubusercontent.com/1226218/100918897-d6108b00-34b7-11eb-8a88-9013c5ec7dbd.png)

Ao tentar remover qualquer filtro, a interface volta para a tela dos mais de 31 M de registros

![image](https://user-images.githubusercontent.com/1226218/100919037-0821ed00-34b8-11eb-959e-42656ee219f2.png)

**Comment by viniciusandrade** [comment]
@renatomurasaki para resolver este caso precisei alterar a implementação da coluna de filtros para contemplar os filtros do wizard porque eles podem ou não estar visiveis para o usuário ... nos meus testes aparentemente esta OK mas como este código é compartilhado por todas as interfaces talvez seja interessante pedir a Rose uma rodada mais de testes para ver se ela identifica algum efeito colateral no uso dos filtros em geral.

**Comment by renatomurasaki** [comment]
@viniciusandrade entendi. Por favor, coordene com a @pintoros estes testes.

**Comment by viniciusandrade** [comment]
Fechando este issue pois foram abertos outros com o resultado dos testes da Rose.
