### ISSUE TITLE
Adicionar link "DB Updates/Help" 

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/iahx-opac#245]
"We will be linking back to the page
https://www.who.int/emergencies/diseases/novel-coronavirus-2019/global-research-on-novel-coronavirus-2019-ncov/

This page is only in English and so all language interfaces on Bireme COVID page will link back to the above link.
(While the link behind the WHO logo also links to this page, I think it is not obvious to searchers that case. 

The  News/Update Icon should be under the languages (option 2) to avoid confusion with being updates and news for WHO (if it were directly under the WHO logo)
The icon presented here was taken from a the internet, so I don’t think we should use it.
Can we have a simple box with words  

**DB Updates/Help**

I don’t have the tools or skills to create an icon. As the link is back to an English only page, we can have the icon only in English."

**Comment by viniciusandrade** [comment]
@renatomurasaki pelo que entendi da mensagem acima eles pediram uma caixa simples com o rótulo **DB Updates/Help** fixa para todos os idiomas da interface e apontando para o mesmo link informado. 

Se for isso esta implementado no ambiente de testes:

https://pesquisa.teste.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov/

Poderia, quando possível, informar se podemos aplicar esta alteração em produção?

Obrigado

**Comment by viniciusandrade** [comment]
@renatomurasaki de acordo com última troca de mensagens foram feitas as seguintes alterações:
- Tradução via Google Translate do rótulo do botão **News/Update/Help** para todas os idiomas da interface
- Alteração do link de destino para diretório One Drive de documentos compartilhados

Agradeço, quando possível, solicitar a validação para publicação.

Obrigado

**Comment by renatomurasaki** [comment]
@viniciusandrade podemos seguir com a implementação. O link a ser usado em todos os idiomas é https://www.who.int/publications/m/item/quick-search-guide-who-covid-19-database

**Comment by viniciusandrade** [comment]
@renatomurasaki, link alterado e botão publicado em produção.

**Comment by renatomurasaki** [comment]
@viniciusandrade muito obrigado!
