### ISSUE TITLE
EVID@Easy - cache Tipo de estudo de avaliação

### ISSUE THREAD

**Issue by pintoros** [bireme/iahx-opac#246]
Independente do idioma e do tipo de estudo selecionado após o primeiro uso, permanece em cache essa opção de tipo de estudo em português.
Exemplo na de pesquisa interface em inglês, mas ocorre o mesmo em espanhol. Obs.: em nenhuma das duas eu havia selecionado este tipo de estudo.
![ex 3 - guarda cache de estudos de avaliação](https://user-images.githubusercontent.com/29313904/102402053-ffa2d980-3fc2-11eb-8f53-a7283ce501f4.JPG)

Browser usado: Mozilla

**Comment by viniciusandrade** [comment]
Mecanismo do cache foi revisado, favor quando possível limpar o cache do navegador e realizar novos testes.

A questão do idioma deve ser considerada como normal do wizard pois nesta versão não será considerada que o usuário estará realizando a troca do idioma da interface enquanto esta usando o wizard.

Obrigado

**Comment by pintoros** [comment]
OK!

**Comment by viniciusandrade** [comment]
Obrigado pela validação.
