### ISSUE TITLE
EVID@Easy - Resultado zerado após selecionar opção de estudo disponível

### ISSUE THREAD

**Issue by pintoros** [bireme/iahx-opac#247]
Eu entendo que só aparecem as opções de estudo que estão disponíveis para o tema.
Em dois exemplos tive o resultado zerado após escolher uma opção de estudo.

Exemplos na imagem
![ex 3 - sem resultado](https://user-images.githubusercontent.com/29313904/102402535-b010dd80-3fc3-11eb-89c3-5df87e265e27.JPG)
![ex 1 - sem resultado](https://user-images.githubusercontent.com/29313904/102402536-b0a97400-3fc3-11eb-8524-665705b58bc9.JPG)

**Comment by viniciusandrade** [comment]
@pintoros, na realidade os passos 1 e 2 estão relacionados a filtros pré-definidos e por isso ao selecionar um contexto de saúde no passo 1 o wizard somente irá mostrar os tópicos de saúde relacionados ao contexto selecionado.

O passo 3 (objetivo de pesquisa) serve para agrupar tipos de estudos em grupos (não esta relacionado a nenhum filtro) e o passo 4 mostra os tipos de estudo deste grupo que são em alguns casos buscas por mais de um campo (no seu exemplo acima tipo de estudo e base dados) e por isso não é possível neste ponto combina-los com os passos 1 e 2 pois dependem da execução de uma busca na base de dados, por isso, o resultado pode sim ser zero.

Espero ter conseguido explicar.

**Comment by pintoros** [comment]
@viniciusandrade eu sei que os passos 1 e 2 tem a ver com os filtros pré-definidos. 
No passo 3 aparecem as perguntas, e no 4 os tipos de estudo de acordo com a resposta. Até aí tudo bem.
Mas é bem frustrante para o usuário clicar em um tipo de estudo relacionado a pergunta que apresente resultado zero.
Sugestão: Pensei que os passos 3 e 4 com eram interdependentes do resultado dos passos 1 e 2. A lógica do usuário vai entender que o sistema faz essa ponte...então seria o caso de desabilitar o clique no tipo de estudo que não apresenta resultado para aquela combinação, mas como não há essa comunicação, a outra sugestão é trabalhar com um texto informativo no passo 4 alertando o usuário que nem nem todos os tipos de estudo listados podem estar disponíveis para aquela opção.

**Comment by viniciusandrade** [comment]
@pintoros entendo as considerações mas acredito que podemos ir melhorando a medida que tivermos outras iniciativas de wizard, pois vai ficar mais claro o que pode ser configurável e o que podemos deixar fixo na interface ... por exemplo se colocamos um texto fixo no passo 4 nada impede que em outro wizard esse passo não tenha esse mesmo comportamento.

Vou fechar este issue por enquanto mas fica registrado para posterior consulta.
