### ISSUE TITLE
EVID@Easy - Interface travando após resultado zerado e/ou demorando para iniciar ao clicar na opção

### ISSUE THREAD

**Issue by pintoros** [bireme/iahx-opac#248]
Pode ser referente a interface de teste, mas ao clicar nessa opção de interface demora mais de 10s para disponibilizar o acesso.
Durante a navegação, após os 2 resultados que zeraram tive que fechar a página e começar de novo. A interface travou.

![ex  2 - Travou depois do resultado zerado - check traduçao](https://user-images.githubusercontent.com/29313904/102402902-39c0ab00-3fc4-11eb-84a1-4ef46c9fbe05.JPG)

**Comment by viniciusandrade** [comment]
@pintoros, realizei ajustes para melhorar o tempo de carregamento das opções da interface wizard, quando possível favor realizar novo teste.

obs: realmente quando a interface estiver no ambiente de produção a tendência é que resposta seja ainda melhor.

**Comment by pintoros** [comment]
Nos testes que fiz hoje, houve melhora na rapidez da resposta.

**Comment by viniciusandrade** [comment]
OK, obrigado pelos testes.
