### ISSUE TITLE
Inclusão do campo ISSN nos formatos XML, CSV e RIS 

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/iahx-opac#253]
Há demanda por uso dos metadados exportados para realização de análises bibliométricas. Há uma dificuldade dos usuários em cruzar os dados das bases com a base de indicadores Journal Impact / Rankings data from Scimago, por exemplo, porque colocamos o nome abreviado das revistas e não temos informação de ISSN.

Vejam mensagem abaixo de usuário da base WHO COVID-19:

```
I find your WHO Covid-19 database (https://search.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov/) very interesting and used the Export feature to extract the records, and would like to link it to Journal Impact / Rankings data from Scimago (https://www.scimagojr.com/) or WebofScience (https://www.webofknowledge.com/).

These can be joined by Journal name; however, the names exported from WHO Covid-19 database appear abbreviated. For example:

"Eur J Phys Rehabil Med" , instead of 

"European journal of physical and rehabilitation medicine"

 Would you have a table that links both abbreviated and full Journal names, or point me to where I could find it?

It seems possible, I noticed that in the WHO Covid search page, if I click on "send to XML" both are shown after some inspection, but only the short name is provided when records are exported in bulk.

Another way would be by ISSN number, but the WHO Covid-19 database doesn't show ISSN. Would you have that relationship (Journal name <-> ISSN number) available somewhere?
```
Entendo que incluir ISSN já ajudaria neste tipo de trabalho, para evitar a troca do nome curto da revista pelo longo. O que acham?

**Comment by viniciusandrade** [comment]
Implementado em https://github.com/bireme/iahx-opac/commit/47c0215e10b792f805f3cb78b6f77a1510de0b46.

TAG no XML:  **is**
TAG no RIS:   **SN**
COLUNA ADICIONADA NO CSV: **ISSN**
