### ISSUE TITLE
Incluir o link de Epistemonikos na interface WHO COVID-19 (igual ao que temos na BVS Regional)

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/iahx-opac#254]
Interface Regional (com link do Epistemonikos)
![image](https://user-images.githubusercontent.com/1226218/108203268-0227c980-7101-11eb-8c3e-8db9a7632341.png)

Interface WHO COVID-19 (sem link do Epistemonikos)
![image](https://user-images.githubusercontent.com/1226218/108203338-22578880-7101-11eb-99d5-2a7cb83768fc.png)

O desafio é que os documentos da COVID, provenientes do Medline, usam o ID da COVID. O link entre Epistemonikos e BVS REgional é via ID original das bases. Entretanto, o ID medline da COVID está presente no campo `alternate_id`, com o prefixo "covidwhomdl-"

**Comment by renatomurasaki** [comment]
@viniciusandrade obrigado! Está ok, pode colocar em produção, por favor.

**Comment by viniciusandrade** [comment]
@renatomurasaki disponível em produção:

https://search.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov/resource/en/covidwho-1059687
