### ISSUE TITLE
Propor layout para mostrar aos usuários do iAHx (WHO COVID-19 e BVS Regional) o relacionamento entre preprint e artigo de periódico publicado

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/iahx-opac#255]
@marcioalvessilva estamos desenvolvendo uma forma de relacionar um documento preprint com o respectivo artigo de periódico publicado. A ideia é fazer algo similar ao que o PMC Europe já está fazendo

![image](https://user-images.githubusercontent.com/1226218/108762827-54b51b80-752f-11eb-92f6-eed93150f601.png)

Repare que há um disclaimer tanto no preprint como no artigo de periódico, permitindo que o usuário possa pular de um para o outro.

Favor propor um layout para que possamos prover a mesma funcionalidade na interface de busca do WHO COVID-19 e da BVS Regional.

**Comment by marcioalvessilva** [comment]
Boa tarde @renatomurasaki !
Segue link para teste - http://mockups.teste.bireme.org/iahx/interna.php

Aguardo feedback!

**Comment by renatomurasaki** [comment]
Márcio, este novo disclaimer precisa conviver com o disclaimer anterior de preprint. Mantenha no mesmo mockup para verificarmos como vai ficar.

**Comment by renatomurasaki** [comment]
@marcioalvessilva Considere que alguns documentos já tem uma informação complementar quando está também indexado em Epistemonikos, como se vê abaixo (Texto a partir de Revisão Sistemática)
![image](https://user-images.githubusercontent.com/1226218/109697777-68830200-7b6d-11eb-9db1-db87af2ec3af.png)

Pode ser que ocorra uma coincidencia entre documentos e também ter esta informação, além do relacionamento entre preprint e artigo de periódico. 

Que tal seguir esse modelo do Epistemonikos e fazer um layout compatível com a situação de ser um artigo indexado em Epistemonikos e que ao mesmo tempo se relaciona com um preprint?

**Comment by marcioalvessilva** [comment]
@renatomurasaki link atualizado 
![image](https://user-images.githubusercontent.com/48724136/109817140-5312e400-7c10-11eb-9cdb-303d0b2568f9.png)

Aguardo mais orientações.

**Comment by renatomurasaki** [comment]
@marcioalvessilva fiquei com dificuldade de ver o texto azul do link no fundo laranja. Que tal manter o mesmo estilo atual do Epistemonikos?

**Comment by marcioalvessilva** [comment]
Bom dia @renatomurasaki!
Link atualizado
![image](https://user-images.githubusercontent.com/48724136/109822374-a50a3880-7c15-11eb-9b9a-ec05ae6f339a.png)

Fico à disposição!

**Comment by renatomurasaki** [comment]
Obrigado, @marcioalvessilva
