### ISSUE TITLE
Desenvolver layout para mostrar o relacionamento entre preprints e artigos de periódicos

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/iahx-opac#256]
Layout de acordo com o que for definido em #255 
Metadado no XML iAHx de acordo com o que for definido em https://github.com/bireme/db-processing/issues/464

**Comment by renatomurasaki** [comment]
@viniciusandrade o @marcioalvessilva desenvolveu uma proposta de layout e está disponível em 

http://mockups.teste.bireme.org/iahx/interna.php

### Textos da relação preprint -> artigo de periódico
**Inglês**
A scientific journal published article is available and it is probably based on this preprint, through the recognition of similarity performed by a machine. Human confirmation is still pending.
**Espanhol**
Un artículo publicado en revista científica está disponible y probablemente es basado en este preprint, por medio del reconocimiento de similitud realizado por una máquina. La confirmación humana aún está pendiente. 
**Português**
Um artigo publicado em periódico científico está disponível e provavelmente é baseado neste preprint, por meio do reconhecimento de similaridade realizado por uma máquina. A confirmação humana ainda está pendente.
### Textos da relação artigo de periódico -> preprint
**Inglês**
This scientific journal article is probably based on a previously available preprint, through the recognition of similarity performed by a machine. Human confirmation is still pending.
**Espanhol**
Este artículo de revista científica es probablemente basado en un preprint previamente disponible, por medio del reconocimiento de similitud realizado por una máquina. La confirmación humana aún está pendiente. 
**Português**
Este artigo de periódico científico é provavelmente baseado em um preprint previamente disponível, por meio do reconhecimento de similaridade realizado por uma máquina. A confirmação humana ainda está pendente.

**Comment by viniciusandrade** [comment]
@renatomurasaki,

Ajuste implementado na página de detalhes. 

Exemplo:
https://search.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov/resource/en/ppbiorxiv-238394

**Comment by renatomurasaki** [comment]
@viniciusandrade obrigado! Me assustei, pois ainda não foi aprovado pela OMS. Era para deixar primeiro no ambiente de testes. Mas pode deixar na produção que já aviso eles.

**Comment by viniciusandrade** [comment]
@renatomurasaki desculpe pensei que já tinha sido aprovado. 

Qualquer problema é só informar que eu desabilito.

**Comment by renatomurasaki** [comment]
@viniciusandrade há um erro no disclaimer. Repare que quando o documento é um preprint, o texto em inglês é:

`A scientific journal published article is available and it is probably based on this preprint, through the recognition of similarity performed by a machine. Human confirmation is still pending.`

Quando o documento é o artigo de periódico, o texto é:

`This scientific journal article is probably based on a previously available preprint, through the recognition of similarity performed by a machine. Human confirmation is still pending.`

**Comment by viniciusandrade** [comment]
@renatomurasaki, OK ajuste realizado.
