### ISSUE TITLE
Botão Evid@Easy não aparece na página de detalhamento do documento

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/iahx-opac#258]
![image](https://user-images.githubusercontent.com/1226218/109025511-8d730300-769d-11eb-8c39-3f4f9264111b.png)

**Comment by viniciusandrade** [comment]
@renatomurasaki  a página de detalhes não possui todos os parâmetros necessários para que o Evid@Easy carregue corretamente e alterar esse comportamento seria complexo.

Neste caso  a solução que encontrei é redirecionar o usuário para página inicial com o wizard aberto. OK?

Exemplo:
https://pesquisa.teste.bvsalud.org/portal/resource/pt/mdl-33685888

Abraços

**Comment by renatomurasaki** [comment]
@viniciusandrade ok, obrigado!
