### ISSUE TITLE
Eventos do Google Analytics - Interface wizard EVID@Easy

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/iahx-opac#260]
Criação de eventos para registrar o passo a passo do Wizard:

Exemplo -> Category = Wizard

```
1) Action = Step 1
2) Label = ODS3 - Saúde e Bem-estar
```

```
1) Action = Step 2
2) Label = Meta 3.2: Reduzir ....
```

**Comment by viniciusandrade** [comment]
@renatomurasaki eventos implementados ... devem começar a aparecer hoje no Analytics no relatório Realtime > Events.

Favor, quando possível, verificar se desta forma esta OK para acompanhamento do uso da ferramenta.

Obrigado.

**Comment by renatomurasaki** [comment]
Os registros dos eventos do passo a passo já estão nas estatísticas do Google Analytics. Parecem ok! Obrigado @viniciusandrade
