### ISSUE TITLE
Criar eventos do Google Analytics para os botões de compartilhamento nas redes sociais

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/iahx-opac#261]
![image](https://user-images.githubusercontent.com/1226218/109821788-17c6e400-7c15-11eb-9cd0-0704016aab58.png)

Priorizar a atualização das interfaces da BVS Regional e WHO COVID-19

**Comment by renatomurasaki** [comment]
@viniciusandrade estamos precisando dessa estatística para apoiar a justificar de contratação do serviço Altmetric.

**Comment by viniciusandrade** [comment]
@renatomurasaki eventos criados com a categoria Social, inclui neste registro também o clique no botão do Dimensions ficando assim:
![social-event](https://user-images.githubusercontent.com/349287/114567575-bcdbd000-9c49-11eb-9eae-6b0ea8e6c4e1.png)

Favor, quando possível, informar se esta OK desta forma. Obrigado.

**Comment by renatomurasaki** [comment]
@viniciusandrade estou de acordo com a lógica de categoria, ação e label. Vou verificar e qualquer coisa reabro este issue. Obrigado!
