### ISSUE TITLE
Alterar tradução em inglês do texto de relacionamento entre preprint e artigo de periódico

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/iahx-opac#262]
### Na visualização do preprint
**DE:** 
A scientific journal published article is available and it is probably based on this preprint, through the recognition of similarity performed by a machine. Human confirmation is still pending.

**PARA:**
A scientific journal published article is available and is probably based on this preprint. It has been identified through a machine matching algorithm, human confirmation is still pending.

### Na visualização do respectivo artigo de periódico
**DE:** 
This scientific journal article is probably based on a previously available preprint, through the recognition of similarity performed by a machine. Human confirmation is still pending.
**PARA:**
This scientific journal article is probably based on a previously available preprint. It has been identified through a machine matching algorithm, human confirmation is still pending.

**Comment by viniciusandrade** [comment]
Textos atualizados.
