### ISSUE TITLE
Integrar o serviço Dimensions na página de detalhes do registro

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/iahx-opac#264]
@viniciusandrade para ampliar nossas ações em termos infométricos e oferecer mais dados aos usuários, poderemos utilizar o serviço gratuito Dimensions. 

Exemplo de site que utiliza Dimensions
![image](https://user-images.githubusercontent.com/1226218/111832538-b028be00-88cf-11eb-89a3-213a6e246070.png)

Quando o usuario passa o mouse por cima do símbolo Dimensions, visualiza o seguinte pop-up
![image](https://user-images.githubusercontent.com/1226218/111832660-e1a18980-88cf-11eb-9a8e-fa7a2369d625.png)

Ao clicar, é enviado para o site Dimensions e vê informação completa sobre citações.

A integração do Dimensions em qualquer página web é dado pela inclusão do seguinte código

`<span class="__dimensions_badge_embed__" data-doi="NUMERO DOI"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>`

Há possibilidade de outras configurações deste botão, disponível em https://badge.dimensions.ai/

Considerando agora a existência do metadado "aid" no XML iAHx, poderemos utilizar este serviço que tratará valor agregado às nossas páginas.

Qualquer dúvida, avise-me.

**Comment by renatomurasaki** [comment]
@viniciusandrade veja se você precisa de mais informação para iniciarmos a implementação deste serviço, por favor. Estou negociando o Altmetric também, entretanto tem custo anual.

**Comment by viniciusandrade** [comment]
@renatomurasaki integração inicial disponível no ambiente de testes para verificação:
Ex.:
https://pesquisa.teste.bvsalud.org/portal/resource/pt/mdl-22539938

Favor informar qual estilo iremos utilizar (círculo ou retângulo) e se é necessário algum ajuste adicional.

Obrigado.

**Comment by renatomurasaki** [comment]
@viniciusandrade excelente! O que acha de testar esta possibilidade abaixo, que já mostra os dados ao lado do símbolo do dimensions?

![image](https://user-images.githubusercontent.com/1226218/113580480-30ebf780-95fc-11eb-8402-083929ac246a.png)

**Comment by renatomurasaki** [comment]
@viniciusandrade a sugestão que fiz no comentário anterior dependerá de como o widget se comportará quando um determinado DOI não tem informação de citações.

**Comment by viniciusandrade** [comment]
@renatomurasaki alterei na teste mas acho que não temos muito controle sobre a posição/layout da legenda.

**Comment by viniciusandrade** [comment]
@renatomurasaki aqui esta um exemplo quando não existe informação de citações:

https://pesquisa.teste.bvsalud.org/portal/resource/pt/mdl-31387792

**Comment by renatomurasaki** [comment]
@viniciusandrade parece-me que o melhor seria o retângulo e sem mostrar os detalhes de citação. Na minha opinião, o retângulo é mais explicativo do que o hexágono, por trazer o nome citations. O que você acha? Se estiver de acordo, pode concluir a integração, inclusive, no iAHx do WHO COVID-19, por favor.

**Comment by viniciusandrade** [comment]
@renatomurasaki OK, de acordo. Implementado em produção.

Ex:
https://pesquisa.bvsalud.org/portal/resource/pt/mdl-22539938

*Obs: Nos meus testes não consegui localizar nenhum artigo na base WHO COVID-19 que retorne dados para o serviço.

**Comment by renatomurasaki** [comment]
@viniciusandrade onde posto testar a integração do dimensions para WHO COVID-19?

**Comment by viniciusandrade** [comment]
@renatomurasaki já esta em produção para todas as páginas de detalhe ... mas conforme indicado acima só irá apresentar o logo do serviço caso existam citações.  

A outra opção é deixar sempre mostrando o logo do serviço com 0 citações, para ficar mais claro alterei na testes para comparação:

https://pesquisa.teste.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov/resource/en/covidwho-1158503

**Comment by renatomurasaki** [comment]
@viniciusandrade ok, sem problemas. Mantenha como você já implementou na produção, ou seja, não mostrar quando não há citação. Encontrei uma referência na COVID-19 com citação:

https://pesquisa.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov/resource/en/covidwho-1155968

**Comment by viniciusandrade** [comment]
@renatomurasaki OK, legal que você encontrou um exemplo na base COVID-19.
