### ISSUE TITLE
Quando o registro bibliográfico não tem resumo, os ícones de compartilhamento em redes sociais não funcionam

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/iahx-opac#267]
Exemplos de registros que os ícones de compartilhamento não funcionam:

https://pesquisa.bvsalud.org/portal/resource/pt/mdl-33789402
https://pesquisa.bvsalud.org/portal/resource/pt/mdl-33789401

**Comment by viniciusandrade** [comment]
@marcioalvessilva você poderia me ajudar com esta questão? fazendo inspect na página me parece que a caixa div="social" esta conflitando com o div do slider e por isso o usuário não consegue clicar no link dos ícones das redes sociais. Obrigado.

**Comment by marcioalvessilva** [comment]
@viniciusandrade no CSS você deve localizar a classe social e inserir o atributo z-index:10 como no exemplo abaixo em negrito

.social{ float: right; width: 40px; margin:0 0 20px 20px; position: sticky; top: 0; margin-top: 38px; **z-index:10**}

**Comment by viniciusandrade** [comment]
@marcioalvessilva valeu, já alterei na CSS.
@renatomurasaki é preciso realizar um shift+reload na página para atualizar a CSS.

**Comment by renatomurasaki** [comment]
@viniciusandrade @marcioalvessilva obrigado! Funcionou!
