### ISSUE TITLE
Atualizar código Dimensions Badge para incluir a possibilidade de uso do PMID quando o DOI estiver ausente

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/iahx-opac#268]
Quando o campo de DOI estiver ausente nos registros bibliográficos da base MEDLINE, é possível utilizar o identificador armazenado no campo PMID.

Basta trocar o parâmetro `data-doi` por `data-pmid`

**Comment by viniciusandrade** [comment]
OK, implementado em (https://github.com/bireme/iahx-opac/commit/cf6580863eb559da24c19e591872e37b235d8495) regra de quando ausente campo DOI chamar serviço Dimensions passando o PMID.

**Comment by renatomurasaki** [comment]
@viniciusandrade perfeito! Já testei e funcionou! Encontrei documentos da década de 60 com citações disponíveis no Dimensions.
