### ISSUE TITLE
Incluir Dimensions Badges na interface de pesquisa do GIM

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/iahx-opac#269]

**Comment by viniciusandrade** [comment]
@renatomurasaki pelo que eu verifiquei o GIM já utiliza o mesmo template do portal regional e não tem customização para a página de detalhes ... desta forma já estaria usando o mesmo código do portal que inclui o Dimensions, mas não consegui localizar nenhum exemplo de referência desta base que ative o badge do dimensions.

**Comment by renatomurasaki** [comment]
@viniciusandrade obrigado. Está ok. Vide exemplo abaixo:

https://pesquisa.bvsalud.org/gim/resource/en/lil-676341

Uso o seguinte método para testar: busco por `aid:*` . Depois ordeno o resultado em ordem crescente de publicação (mais chance de ter sido citado).
