### ISSUE TITLE
O icone de carregamento da página não está sendo mostrado na interface GIM

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/iahx-opac#270]
A interface iAHx GIM está sem o ícone de carregamento (hexágonos) da página, como mostra a figura abaixo:
![image](https://user-images.githubusercontent.com/1226218/117345785-53806300-ae7d-11eb-8b03-3899ba2fa079.png)

O comportamento esperado é (print do iAHx Regional)

![image](https://user-images.githubusercontent.com/1226218/117345957-862a5b80-ae7d-11eb-9430-f30cfb944380.png)

**Comment by marcoslmori** [comment]
Sincronizado para a produção

**Comment by renatomurasaki** [comment]
Obrigado. Testei e agora aparece!
