### ISSUE TITLE
Campo AD na exportação de registros 

### ISSUE THREAD

**Issue by pintoros** [bireme/iahx-opac#271]
*Solicito a inclusão do campo AD na exportação de registros em diferentes formatos, principalmente .RIS

Transcrição da mensagem do usuário enviada para o Vinícius/Marcelo
"Estou trabalhando em um projeto de pesquisa que usa a BVS como fonte de dados biliográficos extraindo os resultados da busca por meio dos arquivos com extensão RIS. Um dos metadados que gostaríamos de estudar no projeto é a afiliação dos autores, especificamente para montar redes de colaboração científica para o campo do conhecimento alvo da pesquisa.
É possível obtermos uma extração destes metadados de afiliação (Tag AD) para um grupo de manuscritos que temos interesse?" 

Eu fiz um teste de exportação de um conteúdo para .RIS (anexo) e esse campo não vem especificado. 
AD (afiliação de autor), preciso saber se é um campo considerado no registro, se não, vou abrir um chamado, pois existe na metodologia, correto?

Rose
-------------------
Resposta do Marcelo para Vinícius,

no XML das IAHx, existem os campos "au" e "afiliacao_autor", como abaixo (id:lil-753812):

    <field name="au">Zarzosa-Norabuena, Edwin</field>
    <field name="afiliacao_autor">Zarzosa-Norabuena, Edwin; Universidad de San Martín de Porres. Facultad de Medicina Humana. Instituto de Investigación. Cen
tro de Investigación de Bioquímica y Nutrición. Lima. PE</field>

    <field name="au">Loja-Herrera, Berta</field>
    <field name="afiliacao_autor">Loja-Herrera, Berta; Universidad de San Martín de Porres. Facultad de Medicina Humana. Instituto de Investigación. Centro d
e Investigación de Bioquímica y Nutrición. Lima. PE</field>

    <field name="au">Salazar-Granara, Alberto</field>
    <field name="afiliacao_autor">Salazar-Granara, Alberto; Universidad de San Martín de Porres. Facultad de Medicina Humana. Instituto de Investigación. Cen
tro de Investigación de Bioquímica y Nutrición. Lima. PE</field>

    <field name="au">Inocente-Camones, Miguel</field>
    <field name="afiliacao_autor">Inocente-Camones, Miguel; Universidad de San Martín de Porres. Facultad de Medicina Humana. Instituto de Investigación. Cen
tro de Investigación de Bioquímica y Nutrición. Lima. PE</field>

O formato RisFormat não contempla o campo "afiliacao_autor"?

Risformat da IAHx:
TY  - JOUR
AU  - Zarzosa-Norabuena, Edwin
AU  - Loja-Herrera, Berta
AU  - Salazar-Granara, Alberto
AU  - Inocente-Camones, Miguel
TI  - Efecto sobre el sistema de la coagulación del zumo de frutas y hortalizas peruanas
TT  - Effect on the clotting system of Peruvian fruit and vegetable juice
JO  - Horiz. méd. (Impresa)
VL  - 15
IS  - 2
SN  - 1727-558X
DB  - LILACS
DP  - http://bvsalud.org/
ID  - lil-753812
LA  -
SP  - 6
EP  - 11
DA  - 2015/04
PY  - 2015
KW  - Humanos
KW  - Animais
KW  - Masculino
KW  - Feminino
KW  - Ratos
KW  - Verduras
KW  - Bebidas Gaseificadas
KW  - Doenças Cardiovasculares
KW  - Agentes de Coagulação
AB  - OBJETIVO: Comprobar el efecto anticoagulante in vitro e in vivo de frutas y hortalizas peruanas e identificar la vía de la coagulación sobre la que actúa. MATERIAL Y MÉTODOS: Se extrajo los zumos de Ananascomosus (L.) Merr, Citrus limonun Risso, Carica papaya L., Alliumsativum L., Allium cepa L. y Zingiber officinale L. Roscoe. Se realizó un estudio in vitro con plasma humano e in vivo administrando el zumo vía oral a ratas por catorce días. La actividad anticoagulante fue evaluada midiendo el tiempo de protrombina (TP) y el tiempo de tromboplastina parcial activado (TTPa), además se determinó el fibrinógeno. RESULTADOS: In vitro los zumos de Ananas y Zingiber prolongaron el TP, Carica el TTPa y los de Citrus, Alliumsativumy cepa ambas pruebas. In vivo los zumos de Allium cepa y Carica prolongaron el TP, Citrus el TTPa, Ananas ambas pruebas. Los zumos de Ananas, Citrus, Allium sativum y Zingiber disminuyeron el fibrinógeno. CONCLUSIÓN: In vitro e in vivo los zumos de Ananascomosus, Citrus limonun, Carica papaya y Allium cepa tienen efecto anticoagulante. Los zumos de Allium sativum y Zingiber officinale,tienen este efecto solo in vitro.
AB  - OBJECTIVE: Verify the anticoagulant effect in vitro and in vivo of Peruvian fruit and vegetable juice and identify the coagulation pathway on which it acts. MATERIAL AND METHODS: Extracted juices of Ananascomosus (L.) Merr, Citrus limonunRisso, Carica papaya L., Allium sativum L., Allium cepa L. and Zingiber officinale L. Roscoe. An in vitro study with human plasma and in vivo administering juice orally to rats for 14 days. Anticoagulant activity was evaluated by measuring the prothrombin time (PT) and partial activated thromboplastin time (APTT), the Fibrinogen was also determined. RESULTS: In vitro juices of Ananas and Zingiber prolonged PT, Carica prolonged APTT and Citrus, Allium sativum and cepa prolonged both tests. In vivo, juices of Allium cepa and Carica prolonged PT, citrus prolonged APTT, and Anannas both tests. The juices of Anannas, Citrus, Allium sativum and Zingiber decreased Fibrinogen. CONCLUSION: In vitro and in vivo Ananascomosus, Citrus limonun, Carica papaya and Allium cepa juices have anticoagulant effect. The juices of Allium sativum and Zingiber officinale, have this effect only in vitro.
UR  - http://www.scielo.org.pe/scielo.php?script=sci_arttext&amp;pid=S1727-558X2015000200002
ER  -
Marcelo Bottura

**Comment by viniciusandrade** [comment]
@renatomurasaki conforme solicitação de pesquisadora gostaria confirmar se podemos adicionar a informação do campo **afiliacao_autor** no formato de exportação RIS no elemento **AD (Author Address)** para todas as instâncias do IAHx? Obrigado.

**Comment by renatomurasaki** [comment]
@viniciusandrade creio que pode. Consegue manter a mesma ordem do AU para garantir a relação entre autor e afiliação?

**Comment by viniciusandrade** [comment]
@renatomurasaki OK vou implementar no arquivos do core. 
Infelizmente na camada do template não tenho como programar e somente consigo apresentar os dados então não teria como implementar lógica de pareamento.

**Comment by viniciusandrade** [comment]
@pintoros campo AD disponível na exportação do formato RIS. 
Favor, quando possível, verificar e informar a usuária.

Obrigado
