### ISSUE TITLE
O ID na exportação CSV não está incluindo o radical da base de dados

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/iahx-opac#272]
Exemplo de exportação da referência bibliográfica 

https://pesquisa.bvsalud.org/portal/resource/pt/mdl-33912962

**Formato RIS**
ID  - mdl-33912962

**Formato CSV**
ID
"33912962"

**Comment by viniciusandrade** [comment]
Correção aplicada.

**Comment by viniciusandrade** [comment]
@renatomurasaki notei que o ID também esta sem prefixo no formato de exportação da base COVIDWHO, como o template foi customizado para adicionar o entry_date ele não pegou o ajuste do core ... posso corrigir lá também ou melhor deixar como esta para evitar atrapalhar algum controle existente deles?

**Comment by renatomurasaki** [comment]
favor corrigir lá também @viniciusandrade

**Comment by viniciusandrade** [comment]
OK, ajuste aplicado na instância COVIDWHO.
