### ISSUE TITLE
Alteração na URL do iAHx dedicado ao índice AIM

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/iahx-opac#279]
A equipe da AFRO/WHO decidiu alterar a URL 

DE:
https://search.bvsalud.org/aim

PARA:
https://search.bvsalud.org/aimafro

**Comment by viniciusandrade** [comment]
@renatomurasaki é preciso realizar redirecionamento das urls de aim para aimafro ou somente alterar a url?

**Comment by renatomurasaki** [comment]
@viniciusandrade o pedido foi de alteração mesmo. O que poderia fazer para mitigar riscos de quebra de link (mesmo sendo recente a criação dessa instância, é fazer o /aim/ redirecionar para /aimafro/

Em relação ao sitemap, por favor, pode solicitar ao @botturam a criação deste sitemap e registro no Google Search Console.

**Comment by viniciusandrade** [comment]
@renatomurasaki redirecionamento realizado. 

Issue criado para sitemap e registro no google search console: https://github.com/bireme/db-processing/issues/547

**Comment by marcoslmori** [comment]
@viniciusandrade , chequei agora e já está produção!  tem alguma ação que eu tenho que fazer?

**Comment by viniciusandrade** [comment]
@marcoslmori favor verificar a questão do Google Analytics.

**Comment by renatomurasaki** [comment]
@viniciusandrade obrigado! @viniciusandrade @marcoslmori o GA ID do AIMAFRO está sendo gerenciado pela equipe da AFRO/WHO. Entendo que se estamos usando o mesmo ID não há problema com a mudança no Google Analytics.

**Comment by marcoslmori** [comment]
documentado a questão do ID do google analytics  http://suporte.bvs.br//ocomon/geral/ticket_show.php?numero=7957&id=20260282162722829015524428

**Comment by viniciusandrade** [comment]
Estou fechando pois o usuário já validou e confirmou que esta OK.
