### ISSUE TITLE
Implementar código para mostrar informação semântica

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/iahx-opac#281]
Aguardar HTML do issue #280

**Comment by renatomurasaki** [comment]
@viniciusandrade assim que implementar no ambiente de testes, favor me avisar.

**Comment by marcioalvessilva** [comment]
@viniciusandrade, mockup atualizado!
http://mockups.teste.bireme.org/iahx/interna.php

git atualizado
https://github.com/bireme/mockups/commit/88b9c027c0a6cb6592b5ce88740ddd6723268b17

Ajuste no arquivo interna.php e style.css

**Comment by renatomurasaki** [comment]
@viniciusandrade exato. Atualizei o outro issue que está em aberto. Vou fechá-lo.
