### ISSUE TITLE
Retirar da interface do WHO COVID-19 o cluster "Collection"

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/iahx-opac#283]
@marcoslmori a equipe de governança do WHO COVID-19, coordenada pela biblioteca da OMS, decidiu retirar o cluster Collection. Favor proceder. Caso não consiga eliminar, pode deixar oculta dentro da opção "Add filters".

**Comment by marcoslmori** [comment]
feito na instancia de teste e solicitado para sincronizar o arquivo config.xml para a produção

http://suporte.bvs.br//ocomon/geral/ticket_show.php?numero=8163&id=i1+eztP09DQvKWKlndsuf+Hkg2s=

**Comment by marcoslmori** [comment]
feito
