### ISSUE TITLE
Código HTML e outros caracteres especiais nos formatos RIS e CSV

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/iahx-opac#285]
Um exemplo:

https://search.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov/resource/en/grc-739541

O código-fonte da página parece estar ok. Mas quando se exporta o registro nos formatos CSV ou RIS, os colchetes se transformam em entidade HTML. Vide arquivos anexos

[export-ris-csv.zip](https://github.com/bireme/iahx-opac/files/7092538/export-ris-csv.zip)

Os usuários que utilizam esses formatos estão reclamando do retrabalho em ajustar esses caracteres.

**Comment by viniciusandrade** [comment]
@renatomurasaki analisando o exemplo me parece que o caracter que esta sendo escapado seria a aspas simples contido no título e também no resumo do documento. 

Fiz um ajuste para não aplicar  o escape do formato como um todo pois existem outro potenciais campos que podem ter este caracter como nos nomes de instituições na afiliação e também no nome da revista.

Este ajuste na  exportação em RIS e CSV estão no abiente de testes, mas como você mencionou no email pode ter efeitos colaterais que não consigo identificar isoladamente. 

Caso seja identificado algum problema teremos que aplicar o ajuste individualmente somente nos campos onde existe um potencial maior de ter este caracter.

Poderia, por gentileza, solicitar a contraparte os testes desta alteração?

Exemplo isolado:

https://pesquisa.teste.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov/?q=id%3Agrc-739541

Obrigado.

**Comment by renatomurasaki** [comment]
@viniciusandrade obrigado! Vou solicitar!

**Comment by renatomurasaki** [comment]
@viniciusandrade solicitado testes no ambiente indicado

**Comment by viniciusandrade** [comment]
Ajustes validados pela contraparte e ajustes publicados em produção.
