### ISSUE TITLE
Acrescentar os links de Termos e Condições de Uso e Política de Privacidade para o IAHx REGIONAL

### ISSUE THREAD

**Issue by marcoslmori** [bireme/iahx-opac#29]
TERMOS E CONDIÇÕES DE USO DOS SITES E SISTEMAS WEB DA BIREME/OPAS

http://politicas.bireme.org/terminos/pt/
http://politicas.bireme.org/terminos/en/
http://politicas.bireme.org/terminos/es/

POLÍTICA DE PRIVACIDADE DOS SITES E SISTEMAS WEB DA BIREME/OPAS

http://politicas.bireme.org/privacidad/pt/
http://politicas.bireme.org/privacidad/en/
http://politicas.bireme.org/privacidad/es/

De forma que possa replicar em todos os IAHx hospedados na BIREME.

**Comment by viniciusandrade** [comment]
Links adicionados no rodapé do portal de pesquisas da BVS.
