### ISSUE TITLE
Interface de busca - Criar botão para usuário aceitar o uso de cookies

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/iahx-opac#294]
Incluir, prioritariamente, nas instâncias que farão uso de dados demográficos, via Google Analytics, pop-up com mensagem padrão e acesso à nossa política de privacidade, explicitando que fazemos uso de cookies, que coletamos dados pessoais, dando a possibilidade do usuário aceitar ou não os cookies.

Ativar este pop-up da forma menos invasiva possível. 

Para implementar este botão é necessário alterar a política de privacidade conforme descrito em https://github.com/bireme/terms-policy/issues/1

**Comment by viniciusandrade** [comment]
Solução implementada utilizando biblioteca JS customizada que mostra barra de aceitação de cookies.
