### ISSUE TITLE
Envio de resultado para o Gmail

### ISSUE THREAD

**Issue by pintoros** [bireme/iahx-opac#298]
Recebemos reclamações de usuários e comprovamos que o envio de resultados originados no iahx regional para o Gmail não está funcionando. Informo que o envio funciona normalmente para o e-mail paho.org e também hotmail (recebido como spam). Parece algo pontual com o Gmail que não recebe nem no spam.

Obrigada

**Comment by alvesmarilda** [comment]
Recebemos devolução de aproximadamente 80 mensagens informando "erro no resultado" para endereços "gmail".

**Comment by viniciusandrade** [comment]
OK, obrigado por abrir o issue.

Estou verificando em conjunto com o ITI, assim que tiver uma posição eu informo por aqui.

**Comment by viniciusandrade** [comment]
@pintoros / @alvesmarilda,

Serviço de envio das mensagens normalizado. Favor quando possível relizar novo teste.

**Comment by alvesmarilda** [comment]
Novo teste efetuado com sucesso. Recebi os resultados de pesquisa em meu gmail.

Obrigada!!

**Comment by viniciusandrade** [comment]
OK, obrigado por confirmar.

**Comment by pintoros** [comment]
Obrigada Vinícius e Marilda!



Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:e5b9451e-04c4-4cec-ada1-581b749f47b4]

________________________________
De: viniciusandrade ***@***.***>
Enviado: sexta-feira, 17 de dezembro de 2021 13:44
Para: bireme/iahx-opac ***@***.***>
Cc: Pinto, Rosemeire (BIR) ***@***.***>; Mention ***@***.***>
Assunto: Re: [bireme/iahx-opac] Envio de resultado para o Gmail (Issue #298)


OK, obrigado por confirmar.

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fiahx-opac%2Fissues%2F298%23issuecomment-996865540&data=04%7C01%7Cpintoros%40paho.org%7C938ed4ee9b074feaf56b08d9c17c8ff1%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637753563034121580%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=nzaUw7FkJ1JAERwhvB4HKRK2YZ2xO0g8QYDceQs4s9o%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4EG6VCOHHL2LAJGJJLURNSIVANCNFSM5J6KQAYQ&data=04%7C01%7Cpintoros%40paho.org%7C938ed4ee9b074feaf56b08d9c17c8ff1%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637753563034121580%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=6jKyFv6cdkzzHtgxpuBvUEskWOGq6oNEfjUXntRbRwY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cpintoros%40paho.org%7C938ed4ee9b074feaf56b08d9c17c8ff1%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637753563034121580%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=dOOeIkHUhatSlZ7bgvv1c7cSX7Nyn9JBg5tL8FTsS8w%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cpintoros%40paho.org%7C938ed4ee9b074feaf56b08d9c17c8ff1%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637753563034121580%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=wpykzONJ1M1kRj9DbPWy9A0cgqGehm5wyeEpDfF0WVI%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.
