### ISSUE TITLE
Dado que o índice do iahx contenha os campos ab_mark", e variações "ab_pt_mark", "ab_es_mark", "ab_*_mark", alterar a interface do iahx para formatar o resumo

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/iahx-opac#30]
Os campos "mark_ab", e variações "mark_ab_pt", "mark_ab_es", "mark_ab_en" contém a marcação `<h2>` para separar ítens tais como: Objetivo, Metodologia, Conclusões dentre outros. Utilizar tal marcação para criar uma apresentação mais agradável no IAHx quando se mostrar o campo de resumo de um documento.

**Comment by viniciusandrade** [comment]
Implementado em ambiente de homologação para validação:

http://pesquisa.homolog.bvsalud.org/portal/resource/pt/lil-789998

**Comment by renatomurasaki** [comment]
E-mail enviado aos stakeholders internos para validação.

**Comment by renatomurasaki** [comment]
@viniciusandrade creio que seria interessante mostrar a aba do idioma que corresponde à interface, ou seja, se estou na interface español, mostrar a aba de RESUMEN, en inglês, mostrar a ABSTRACT.

**Comment by sousajul** [comment]
@renatomurasaki a nova proposta de resumo estruturado é um grande avanço, assim como, a junção dos resumos em abas.

Quanto ao resumo estruturado, minhas sugestões são:
- Diminuir um pouco o tamanho da fonte das seções, considerando que as mesmas já estão em caixa alta. 
- Diminuir o espaçamento (largura) da linha na aba onde está escrito RESUMO, RESUMEN e ABSTRACT.

**Comment by pintoros** [comment]
@renatomurasaki,muito bom! um diferencial e um ganho para os nossos usuários de LILACS! 
Reforço a sugestão da Juliana, ainda tiraria o negrito dos títulos das seções ou adotaria caixa baixa, mantendo o mesmo tamanho da fonte do título do documento.

**Comment by viniciusandrade** [comment]
Ajustes realizados e aplicados no ambiente de produção.
