### ISSUE TITLE
Update WHO link on the French search page 

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/iahx-opac#303]
On the French search page ( https://search.bvsalud.org/aimafro/?lang=fr ), please replace the hypertext link of the " Organisation Mondiale de la Santé " logo with: https://indexmedicus.afro.who.int/fr/index.html . This will allow French speaking users to be redirected to the French homepage by clicking on the logo.

**Comment by viniciusandrade** [comment]
Link replaced.

**Comment by botturam** [comment]
@viniciusandrade há uma alteração ainda sobre esse chamado, segundo o Mike:

For the observation: Regarding the point 3- related to French search page the change on hyperlink is effective but there is a bit error on the page title/banner. The translation of AIM in French is Index Medicus Africain (IMA) , not Index Africain Medicus (AIM). Thanks to resolve

**Comment by viniciusandrade** [comment]
@botturam ajuste realizado no título da página em francês.
