### ISSUE TITLE
Tradução de labels Evid@Easy pt, en, es, fr

### ISSUE THREAD

**Issue by pintoros** [bireme/iahx-opac#306]
Solicito ajustar a tradução dos labels pt e en de navegação do Evid@Easy de acordo com a tabela em anexo.
Os idiomas es e fr estão em fase de revisão. Abrirei outro issue quando estiverem disponíveis.

[LABEL - EVID-EASY_rev-pt-en.docx](https://github.com/bireme/iahx-opac/files/8327538/LABEL.-.EVID-EASY_rev-pt-en.docx)

**Comment by pintoros** [comment]
Segue a versão pt, es, en e fr revisada para aplicação nos labels de navegação do EVID@Easy
@marcioalvessilva @marcoslmori @viniciusandrade 

[Labels_Navegacao.docx](https://paho.sharepoint.com/:w:/r/sites/BIR/TC/TC/Projetos/REGIONAL/Evid@Easy/Labels_Navegacao.docx?d=wd0c8f42788da4e76920495347b36a05e&csf=1&web=1&e=fcvYHs)

**Comment by marcoslmori** [comment]
Aberto um chamado no ocomon para documentação  8726

http://suporte.bvs.br//ocomon/geral/ticket_show.php?numero=8726&id=tRuXeyt4zr0f61shxZ%2BPqUGoQSA%3D

**Comment by marcioalvessilva** [comment]
Finalizado!
