### ISSUE TITLE
Nova proposta de arquitetura da página de visualização dos metadados de um documento no iAHx

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/iahx-opac#31]

**Comment by renatomurasaki** [comment]
![visualizacao-pagina-doc-iahx](https://user-images.githubusercontent.com/1226218/32296546-a7cab600-bf33-11e7-960d-6b795d395eaa.png)

**Comment by viniciusandrade** [comment]
Layout substituido por nova proposta e implementado em #69
