### ISSUE TITLE
Incluir dados de licenças no registro detalhado de registros bibliográficos

### ISSUE THREAD

**Issue by suelisuga** [bireme/iahx-opac#310]
Solicito inclusão de informação de licença contida em registros bibliográficos para ações relacionada à transparência e integridade de dados.

O campo licenças possui tabela controlada, porém não é obrigatório.
![image](https://user-images.githubusercontent.com/13105683/167931530-e01bed32-cc14-4264-a06c-290eaf7b49f5.png)

Então penso que uma possível implantação seja apresentar o dado quando estiver preenchido (há documentos em que não há nenhuma informação do tipo de licença) OU quando não estiver preenchido, apresentar: "Licença não informada". Aparentemente a primeira sugestão me parece a melhor.

Segue informação conforme presente no Django Admin:
![image](https://user-images.githubusercontent.com/13105683/167931900-0792008e-4348-41cb-9bef-ccdfc4b39eb6.png)

E no FI-Admin:
![image](https://user-images.githubusercontent.com/13105683/167930690-5883ca7e-9efb-4f42-8019-845dd4b5567c.png)

Registro detalhado:
![image](https://user-images.githubusercontent.com/13105683/167932020-c22d7556-385a-4587-b76e-f40f5b3e10c5.png)

Solicito que @pintoros avalie necessidade de geração de índice e @Lizbiruel de incluir essa informação também presente em OER.

Vou avaliar se outras FIs necessitam de inclusão desse campo em seu registro.

Muito obrigada!

**Comment by suelisuga** [comment]
@viniciusandrade pf priorizar esta atividade pois é relacionada a PTB BIR.03.05

**Comment by suelisuga** [comment]
@viniciusandrade Encerrei o #322 pq esse já estava vigente.

**Comment by viniciusandrade** [comment]
@suelisuga informação adicionada no ambiente de testes, quando possível favor validar para ser atualizado em produção:

exemplo:
https://pesquisa.teste.bvsalud.org/portal/resource/pt/lil-610239

**Comment by suelisuga** [comment]
@viniciusandrade o dado de licença creative commons  apareceu corretamente, porém quebrou a informação de Resumo.

Na produção o resumo aparece:
![image](https://user-images.githubusercontent.com/13105683/205989714-66db9fba-629e-4456-86a5-42e5abb5f015.png)


Obrigada!

**Comment by viniciusandrade** [comment]
@suelisuga obrigado pela verificação.

@marcioalvessilva quando possível poderia dar uma olhada para ver se consegue entender porque quebrou o layout desta página?

Obrigado

**Comment by marcioalvessilva** [comment]
@viniciusandrade a classe do primeiro item esta escrito errado "**nav-linkactive**" o correrto é "**nav-link active**"

**Comment by viniciusandrade** [comment]
@marcioalvessilva obrigado, correção aplicada.

@suelisuga informação disponível em ambiente de produção.
