### ISSUE TITLE
Indicar marcação para o ID google analytics G4 no config.xml

### ISSUE THREAD

**Issue by marcoslmori** [bireme/iahx-opac#311]
Para iniciar o processo de adicionar o ID google G4 nas instancias de IAHx da BIREME

**Comment by viniciusandrade** [comment]
@marcoslmori parâmetro definido como ```<google_analytics_GA4_id></google_analytics_GA4_id>```

Favor solicitar ao ITI a criação do ID para alguma instância para que eu possa implementar a parte do código para envio dos dados.

Obrigado

**Comment by marcoslmori** [comment]
Agregado a linha sugerida pelo @viniciusandrade no config.xml da instância do Portal Regional e já está em produção. Informar quando dar continuidade em outras instâncias de IAHx

**Comment by viniciusandrade** [comment]
@marcoslmori fiz uma revisão no código e me parece que ele já é compatível com a versão G4 do analytics, bastando substituir o código no próprio elemento <google_analytics_tracking_id>.

Podemos já substituir o código pelo novo uma vez que em 01/07/23 os dados irão parar de ser processados no perfil antigo?

**Comment by marcoslmori** [comment]
https://pesquisa.bvsalud.org/portal/ - G-5KNHPFTHJ8 -  (9038) - em fase sincronização para a produção
https://pesquisa.bvsalud.org/cns-br/ - G-ZPE5FDN5W3 - (9039) - em fase sincronização para a produção
https://pesquisa.bvsalud.org/honduras/ - G-77RD5XHY80 - (9040) - em fase sincronização para a produção

Logo que o ITI atualizar a produção atualizo aqui

**Comment by marcoslmori** [comment]
https://pesquisa.bvsalud.org/portal/ - G-5KNHPFTHJ8 - (9038) - em fase sincronização para a produção
versão nova
<google_analytics_tracking_id>G-5KNHPFTHJ8</google_analytics_tracking_id>
STATUS: OK em produção

https://pesquisa.bvsalud.org/cns-br/ - G-ZPE5FDN5W3 - (9039) - em fase sincronização para a produção
versão nova
<google_analytics_tracking_id>G-ZPE5FDN5W3</google_analytics_tracking_id>
STATUS: OK em produção

https://pesquisa.bvsalud.org/honduras/ - G-77RD5XHY80 - (9040) - em fase sincronização para a produção
Processo efetuadO incorretamente
STATUS: solicitado ao ITI fazer novamente

**Comment by marcoslmori** [comment]
@viniciusandrade fiz um mapeamento de versões dos iahx  https://paho.sharepoint.com/:x:/r/sites/BIR/ADM/ITS/Infraestrutura/Topologia/Instancias/InstanciasXGoogleAnalytics.xlsx?d=w3bd2d75cb86a4b49845c7f8d4fbe51d4&csf=1&web=1&e=4Dt8qj

**Comment by marcoslmori** [comment]
Verificado em> 27/02/2023

https://pesquisa.bvsalud.org/honduras/ - G-77RD5XHY80 - (9040) - em fase sincronização para a produção
Processo efetuadO incorretamente
STATUS: solicitado ao ITI fazer novamente

Continua sendo feito errado

**Comment by marcoslmori** [comment]
Verificado em> 27/02/2023

https://pesquisa.bvsalud.org/honduras/ - G-77RD5XHY80 - (9040) - em fase sincronização para a produção
Processo efetuado incorretamente
STATUS: OK em produção

**Comment by marcoslmori** [comment]
Até o mes 7 será ajustado para o código para os dois marcadores
@marcoslmori  ==> ira tentar o mesmo ou criar um novo tag - Aguardar testes do vinicius

**Comment by marcoslmori** [comment]
Abrir chamado para o ITI para analizar porque náo mostra a estatistica para mori e vinicius

**Comment by viniciusandrade** [comment]
@marcoslmori foi realizado ajuste no código para levar em consideração que o elemento ```<google_analytics_tracking_id>``` pode ter vários valores. 

Favor ajustar o config.xml das instâncias v2 indicando o código antigo e também o novo, conforme exemplo:
```
<google_analytics_tracking_id>UA-624952-15</google_analytics_tracking_id>
<google_analytics_tracking_id>G-5KNHPFTHJ8</google_analytics_tracking_id>
```

**Comment by marcoslmori** [comment]
Versão 1
homeopatia(9067) - em fase de sincronização 

versão 2 
cns-br (9065) - em fase de sincronização 
honduras (9066) - em fase de sincronização

**Comment by marcoslmori** [comment]
Versão 1
https://pesquisa.bvsalud.org/homeopatia/ - em Produção:  verificar mais tarde

Versão 2
https://pesquisa.bvsalud.org/honduras/ - em Produção:  validação UA=OK - GA-4=OK
https://pesquisa.bvsalud.org/cns-br/   - em Produção:  validação UA=OK - GA-4=OK - mas dá 0 usuários

**Comment by marcoslmori** [comment]
@viniciusandrade todas as versões 2 do IAHx foram insertados os dois IDS, GUA e GA4.  Apenas 3 a 4 instancias tem comportamento fora do padrão!  São os que estão em amarelo.  Da versão 1, foi adicionado também os dois IDs na instância https://pesquisa.bvsalud.org/homeopatia/  mas **somente o GA4-funciona**

**Comment by marcoslmori** [comment]
https://paho.sharepoint.com/:x:/s/BIR/EVzX0jtquElLhFx_jU--UdQBQg1kS3eDzXC7QhMIN5Bq4g?email=morimarc%40paho.org&e=4%3Atv0Swq&at=9&CID=ecf93f65-1ed0-f401-51bd-b93bbaf4604a

**Comment by marcoslmori** [comment]
https://paho.sharepoint.com/:x:/r/sites/BIR/ADM/ITS/Infraestrutura/Topologia/Instancias/[InstanciasXGoogleAnalytics.xlsx](https://paho.sharepoint.com/:x:/r/sites/BIR/ADM/ITS/Infraestrutura/Topologia/Instancias/InstanciasXGoogleAnalytics.xlsx?d=w3bd2d75cb86a4b49845c7f8d4fbe51d4&csf=1&web=1&e=N0szMU)?d=w3bd2d75cb86a4b49845c7f8d4fbe51d4&csf=1&web=1&e=N0szMU

**Comment by marcoslmori** [comment]
@viniciusandrade, OK, vou configurando as instâncias e monitorando e informo aqui o andamento

**Comment by viniciusandrade** [comment]
Acredito que esta atividade já esteja concluída. Caso tenha tenha faltado algo favor re-abrir.
