### ISSUE TITLE
Ao atualizar de versão o IAHx não mantêm a estrutura hierárquica do cluster de tema (tag_sp) - Instancia de Saúde Pública

### ISSUE THREAD

**Issue by marcoslmori** [bireme/iahx-opac#312]
Instancia de Produção  -  Versão antiga
![image](https://user-images.githubusercontent.com/10047460/170763129-19feb60a-de3c-4407-910c-c6c962d27d33.png)

Instancia de Teste  - Nova versão
![image](https://user-images.githubusercontent.com/10047460/170763236-192e9db8-b179-4fa6-8927-70327054a33d.png)

/////////////////////////////////////////////
Config.xml 
<cluster>tag_sp</cluster>

Texts.ini 
[REFINE]
tag_sp="Temas"

[REFINE_tag_sp]

ambiente_e_saude="Ambiente e saúde"
saude_ocupacional="Saúde ocupacional"
poluicao_ambiental="Poluição ambiental"
educacao_ambiental="Educação ambiental"
politica_e_planejamento_ambiental="Política e planejamento ambiental"
legislacao_ambiental="Legislação ambiental"
desenvolvimento_sustentavel="Desenvolvimento sustentável"
desastres_ambientais="Desastres ambientais"
agua_ar_solo="Água, ar, solo"
saneamento_basico="Saneamento básico"
residuos="Resíduos"
atencao_a_saude="Atenção à saúde"
promocao_e_prevencao_em_saude="Promoção e prevenção em saúde"
atencao_basica_a_saude="Atenção básica à saúde"
media_complexidade="Média complexidade"
alta_complexidade="Alta complexidade"
assistencia_farmaceutica="Assistência farmacêutica"
programas_e_acoes="Programas e ações"
epidemiologia="Epidemiologia"

**Comment by marcoslmori** [comment]
@viniciusandrade alguma atividade que eu tenho que fazer?

**Comment by marcoslmori** [comment]
@viniciusandrade e @botturam achei uma instancia que também tem estrutura hierárquica no tema

https://pesquisa.bvsalud.org/controlecancer/

Config.xml
<cluster default="true">tag_controlecancer</cluster>

texts.ini em portugues

[REFINE_tag_controlecancer]

cuidados_paliativos="Cuidados Paliativos"
epidemiologia="Epidemiologia"
incidencia="Incidência"
morbidade="Morbidade"
mortalidade="Mortalidade"
prevencao_e_fatores_de_risco="Prevenção e Fatores de Risco"
agentes_cancerigenos="Agentes Cancerígenos"
alcoolismo="Alcoolismo"
alimentacao="Alimentação"
atos_sexuais="Atos Sexuais"
hereditariedade="Hereditariedade"
radiacao_solar="Radiação Solar"
tabagismo="Tabagismo"
saude_da_mulher="Saúde da Mulher"
colo_do_utero="Colo do Útero"
mama="Mama"
tipos_de_cancer="Tipos de Câncer"
boca="Boca"
colo_do_utero="Colo do Útero"
colon_e_reto="Cólon e Reto"
esofago="Esôfago"
estomago="Estômago"
leucemia="Leucemia"
mama="Mama"
outros_tipos="Outros Tipos"
pele="Pele"
prostata="Próstata"
pulmao="Pulmão"
tratamento="Tratamento"
assistencia_farmaceutica="Assistência Farmacêutica"
cirurgia_oncologica="Cirurgia Oncológica"
quimioterapia="Quimioterapía"
radioterapia="Radioterapia"
transplante_de_medula_ossea="Transplante de Medula Óssea"


Aparentemente parece igual.  
Tem alguma dica onde deve ser ajustado para que aparece na instancia de saúde pública?

**Comment by viniciusandrade** [comment]
@marcoslmori ambiente de teste atualizado com ajuste para apresentar o checkbox nos subtemas, quando possivel favor verificar.

![image](https://user-images.githubusercontent.com/349287/182923089-fc9c0280-a988-467e-9743-6dee204336fd.png)

**Comment by marcoslmori** [comment]
Ok, vini, me parece OK, vou validar com a contraparte, obrigado

**Comment by marcoslmori** [comment]
@viniciusandrade ,para documentar, você pode nos informar o que foi ajustado? @botturam

**Comment by viniciusandrade** [comment]
Opa @marcoslmori foram ajustes no próprio template da aplicação e não foi necessário nenhum ajuste no índice ou na configuração.

**Comment by marcoslmori** [comment]
@botturam
