### ISSUE TITLE
Link de acesso ao qualificador no DeCS está inacessível

### ISSUE THREAD

**Issue by suelisuga** [bireme/iahx-opac#314]
Estava testando indexação de documentos sobre varíola dos macacos e tentei acessar a definição do qualificador /instrumentação, porém não consegui acessar. Veio a tela a seguir:

![image](https://user-images.githubusercontent.com/13105683/171059739-b84caee7-5b9b-4685-b2ee-a109edf0e2c6.png)

Para esclarecer, cliquei nesses links de qualificadores que ficam na parte inferior do descritor. Para indexação é fundamental acessar a definição desses qualificadores.

![image](https://user-images.githubusercontent.com/13105683/171059827-bc29b328-c258-45f2-a690-b351a42446de.png)

Obrigada

**Comment by viniciusandrade** [comment]
@suelisuga correção realizada do link. 

Obrigado
