### ISSUE TITLE
Nova opção de informação na lista de tópicos de um filtro

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/iahx-opac#318]
@marcioalvessilva precisamos de uma ajuda sua para implementar uma nova opção que ficará ao lado de cada um dos tópicos apresentado abaixo de um filtro ... esta opção será um link que abrirá um popup com os detalhes deste deste filtro

![image](https://user-images.githubusercontent.com/349287/186480430-59aa7c44-28d6-4a81-84a8-85f3bc2d6cad.png)

**Comment by marcioalvessilva** [comment]
Olá @viniciusandrade 
exemplo publicado no mockup
http://mockups.teste.bireme.org/iahx/

modificações nesse commit
https://github.com/bireme/mockups/commit/06c5f96cb147dc6e9537944145367df4b6725013

Caso precise de ajuda para implementar me chama
- Inserir um bloco de código no arquivo CSS style.css
- Inserir um bloco de código no arquivo js/main.js 
- Inserir o icone depois do label
- Criei um arquivo separado chamado info.php
- Incluir ele no index.php

**Comment by viniciusandrade** [comment]
Obrigado @marcioalvessilva ajustes de layout foram aplicados em ambiente de testes  chamando primeiramente um popup ... caso seja aprovado a implementação daremos seguimento para tentar implementar a opção de sidebar.

**Comment by viniciusandrade** [comment]
@marcioalvessilva ajuste aplicado em produção para a base WHO COVID. 
Vou fechar o issue e caso seja necessário a implementação do sidebar eu abro novamente e te peço uma ajuda.

Obrigado
