### ISSUE TITLE
Customização IAHx Brisa

### ISSUE THREAD

**Issue by marcioalvessilva** [bireme/iahx-opac#326]
Olá @marcoslmori  - Substituir arquivo CSS "styleCustom.css" e inserir imagens
arquivos - [atualização.zip](https://github.com/bireme/iahx-opac/files/9903819/atualizacao.zip)

Ajuste no header
![image](https://user-images.githubusercontent.com/48724136/199080884-ab49f01b-be6f-444a-a9cd-67efc18302f9.png)

Ajuste no footer
![image](https://user-images.githubusercontent.com/48724136/199080945-3c58f672-b0ad-487c-82e1-5f26fc1b0e48.png)

**Comment by marcoslmori** [comment]
Feito, validar

**Comment by marcioalvessilva** [comment]
Concluído!
