### ISSUE TITLE
Funcionalidade de impressão e exportação  no registro detalhado está imprimindo/exportando todos registros da base de dados

### ISSUE THREAD

**Issue by marcoslmori** [bireme/iahx-opac#33]
Entrando no registro detalhado 

![image](https://user-images.githubusercontent.com/10047460/33767682-e1e3bbc8-dc09-11e7-8e07-f4140b0960ae.png)

Escolhendo imprimir ou exportar

Escolhendo essa página: 

![image](https://user-images.githubusercontent.com/10047460/33767748-37768886-dc0a-11e7-909a-6ba6dd757066.png)

O resultado dessa funcionalidade  é a geração  de todos os registros da  base de dados

**Comment by marcoslmori** [comment]
A prova foi feito na instancia de Produção do portal e no que se refere a quantidade de registro provavelmente o limite dos 300 registros. 

Foi feito também no resultado da pesquisa  e aparentemente os registros que aparecem na impressão  não tem haver com o resultado da pesquisa.

**Comment by marcoslmori** [comment]
Fiz o teste somente no navegador chrome

**Comment by viniciusandrade** [comment]
Correção aplicada e arquivos atualizados em produção.

É necessário realizar um refresh da página de detalhes para que o navegador carregue o novo arquivo de funções.
