### ISSUE TITLE
Mudar nome de categoria VS

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/iahx-opac#331]
Favor mudar o nome da categoria Vigilância Sanitária para VIGILÂNCIA EM SAÚDE, com base em documentação descrita em https://paho.sharepoint.com/:b:/r/sites/BIR/TC/TC/Processos/Terminologias/DeCS/Categorias%20exclusivas/VS/Email%20%E2%80%93%20VS-2008.pdf?csf=1&web=1&e=FLRM1H

EN: Surveillance in Public Health
PT-BR: Vigilância em Saúde
ES: Vigilancia de la Salud
FR: Surveillance de la santé publique

**Comment by viniciusandrade** [comment]
Realizado ajuste na versão 2 da API. 
Esta versão ainda não esta em uso na opção de localizar descritor do DeCS (iAHx e FI-ADMIN) pois estamos realizando testes adicionais.

**Comment by viniciusandrade** [comment]
Atualizado em produção.
