### ISSUE TITLE
MTyC recorte

### ISSUE THREAD

**Issue by pintoros** [bireme/iahx-opac#35]
Solicito reprocessar o recorte das bases de dados da instância  [http://pesquisa.bvsalud.org/mtyc](url)
O documento com o novo recorte está disponível em:
[https://bir-fc.paho.org/TC/TC/Projetos/NICARAGUA/Temas-estrategias/EXTRATEGIAS%20MTyC%20-%202018.xlsx](url)

**Comment by botturam** [comment]
https://bir-fc.paho.org/TC/TC/Projetos/NICARAGUA/Temas-estrategias/ESTRATEGIAS%20MTyC%20-%202018.xlsx

**Comment by botturam** [comment]
estratégia geral disponível para processamento em:

serverofi5:/bases/lilG4/bvs.mtc/MTC.sch

Caso seja muito grande, foi também particionada em 4 partes, na planilha do comentário acima.

**Comment by botturam** [comment]
A estratégia Geral precisa ser revisada, pois seu resultado é de apenas 1.168.836 docs, em comparação com os 1.664.831 docs informados na planilha do File Cabinet no post acima. Entretanto, a soma das 4 estratégias parciais está coerente.

**Comment by botturam** [comment]
Processamento final em curso. Previsão para 5f, em homologação.

Já há dados para serem testados em:

pesquisa.homolog.bvsalud.org/mtyc/

**Comment by pintoros** [comment]
O arquivo atual e revisado dos clusters, está disponível em https://bir-fc.paho.org/TC/TC/Projetos/NICARAGUA/Temas-estrategias/ESTRATEGIAS%20MTyC%20-%20processamento.xlsx 
Dados testados em homolog = OK

**Comment by pintoros** [comment]
Arquivo dos labels para tradução para  português e inglês em https://bir-fc.paho.org/TC/TC/Projetos/NICARAGUA/Temas-estrategias/LABELS%20MTyC_port_ing.xlsx

**Comment by botturam** [comment]
processamento concluído na data do lançamento da BVS-MTC
