### ISSUE TITLE
BVS MTCI - Busca por descritor de assunto não retorna resultados

### ISSUE THREAD

**Issue by marcoslmori** [bireme/iahx-opac#358]
![image](https://github.com/bireme/iahx-opac/assets/10047460/eadb80e8-dfac-4361-b732-f010ce64651c)

**Comment by marcoslmori** [comment]
atualizar chamado no ocomon @marcoslmori 
http://suporte.bvs.br//ocomon/geral/ticket_show.php?numero=9637&id=mYQkBXJqlTKPJX7GwyPc%2FvYiF0g%3D

**Comment by marcoslmori** [comment]
Na instância de teste está funcionando. https://pesquisa.teste.bvsalud.org/mtci/

@viniciusandrade, será que falta alguma configuração para a produção?

**Comment by viniciusandrade** [comment]
@marcoslmori ajuste realizado ... na pasta **config** o arquivo **config-mail.php** precisa ser uma cópia (ou link) do config do portal pois agora para acesso a API do DeCS é necessário um token que fica neste arquivo.

**Comment by marcoslmori** [comment]
Valeu!! Vini!  documentado!!

**Comment by marcoslmori** [comment]
validado
