### ISSUE TITLE
IAHx GIM - Detalhe da Pesquisa 

### ISSUE THREAD

**Issue by alvesmarilda** [bireme/iahx-opac#360]
Recebemos a mensagem abaixo através do Livezilla.

Solicito manter a caixa detalhe da pesquisa no mesmo padrão do portal regional.

Nome:Contato BIREME
E-mail:tejewell@uw.edu
Sujeito:[06ECCB2798CB] - Ticket: 15449 - subject: [extra tw:() in search details in Global Index Medicus] - BIREME Online Service
Hi Teresa Jewell,

Thank you for getting in touch with us.

We have received your message and will be responding to your enquiry as soon as possible.

-------------------------------------------------------------
Date: 2024-04-18
-------------------------------------------------------------
Name: Teresa Jewell
Email: tejewell@uw.edu
Subjetc: extra tw:() in search details in Global Index Medicus
Professional practice area: Information Science
Country:US
Group: Atendimento
-------------------------------------------------------------
Greetings,
When I run a search in Global Index Medicus, the Search Details box shows an extra tw:( ) enclosing the search string.
(mh:(B03.440.180* OR C01.150.252.400.177)) appears as tw:((mh:(b03.440.180* OR c01.150.252.400.177)))
This does not affect the results but it confuses my patrons.
It does not happen in VHL Regional Portal. Can it be fixed in Global Index Medicus?

Thank you,
Teresa Jewell
University of Washington Health Sciences Library

Obrigada!

**Comment by viniciusandrade** [comment]
@alvesmarilda ajuste realizado, quando possível favor informar a usuária. Obrigado.
