### ISSUE TITLE
Labels das abas  iAHx

### ISSUE THREAD

**Issue by pintoros** [bireme/iahx-opac#371]
**Na aba LILACS Plus** incluir algum elemento que possa ser linkado para informação no Portal Regional, sobre essa coleção.

PT
LILACS Plus 
Literatura científica e técnica da América Latina e Caribe

Literatura Global
Coleção de bases de dados bibliográficas da BVS

Outras Fontes de Informação
Perguntas e respostas-SOF, Sites-LIS, Multimídia e Recursos educacionais-CVSP

ES
LILACS Plus
Literatura científica y técnica de América Latina y el Caribe.

Literatura Global
Colección de bases de datos bibliográficas de la BVS

Otras Fuentes de Información
Preguntas y respuestas-SOF, Sitios-LIS, Multimedia y Recursos educativos-CVSP

EN
LILACS Plus
Scientific and technical literature from Latin America and the Caribbean

Global Literature
Collection of bibliographic databases of the VHL

Other Information Sources
Questions and answers-SOF, Websites-LIS, Multimedia and Educational resources-VCPH

**Comment by viniciusandrade** [comment]
Favor informar novos rótulos levando em consideração que agora só teremos 2 abas para o Portal Regional.

**Comment by pintoros** [comment]
Considerando a retirada da 3a aba, segue labels corrigidos

PT
LILACS Plus
Literatura científica e técnica da América Latina e Caribe

Literatura Global
Coleção de bases de dados da BVS

ES
LILACS Plus
Literatura científica y técnica de América Latina y el Caribe.

Literatura Global
Colección de bases de datos de la BVS


EN
LILACS Plus
Scientific and technical literature from Latin America and the Caribbean

Global Literature
Collection of databases of the VHL

**Comment by viniciusandrade** [comment]
Ajustes no texto realizadas no ambiente de testes.

**Comment by veronicaabdala** [comment]
Novos labels:

PT
Coleção LILACS Plus
Coleção completa da BVS

ES
Colección LILACS Plus
Colección completa de la BVS

EN
LILACS Plus
Complete collection of the VHL

**Comment by viniciusandrade** [comment]
@veronicaabdala, textos atualizados no ambiente de testes.

Conforme solicitado pela @suelisuga foi movido o texto secundário das abas para texto "alt" (alternativo) que é mostrado quando o usuário passa o mouse sobre o título da aba.

**Comment by veronicaabdala** [comment]
ok, de acordo

**Comment by viniciusandrade** [comment]
Link para icones de ajuda:
https://github.com/bireme/wordpress-themes/issues/219#issuecomment-2426824108
