### ISSUE TITLE
Erro nos totais apresentados nas TABS ao usar a busca por filtros

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/iahx-opac#385]
Problema relatado pela @alvesmarilda :

![image](https://github.com/user-attachments/assets/26c2898c-cea2-4bbe-ac00-2c06a11d9d36)

Quando selecionado a aba Lilas PLUS aparece 2 resultados iguais nas abas:

![image](https://github.com/user-attachments/assets/b9f9e1d0-0193-4430-b0fc-2222e5795b7e)

**Comment by viniciusandrade** [comment]
@alvesmarilda / @pintoros ambiente de testes atualizado para correção deste comportamento. 

Favor, quando possível realizarem novos testes relativos ao uso das abas no sistema. Obrigado.

**Comment by alvesmarilda** [comment]
Teste ok! Validado no ambiente: https://pesquisa.teste.bvsalud.org/portal/

Obrigada

**Comment by viniciusandrade** [comment]
@alvesmarilda, obrigado pela validação. 

Os ajustes foram aplicados no ambiente de produção, quando possível, favor realizar um novo teste na produção e estando tudo OK favor fechar este issue.

Obrigado.

**Comment by alvesmarilda** [comment]
Efetuado teste na produção.   Ok!

Obrigada
