### ISSUE TITLE
Alterar o link do Título da Revista para o novo Portal de Revista

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/iahx-opac#390]
No display do registros artigo de revista que tem o link no título da revista para o portal de revista, por favor, alterar  do antigo para o novo, 

<img width="403" alt="image" src="https://github.com/user-attachments/assets/4c89dc52-57a7-43c2-b250-a206df67ffc3">

Atualmente:
http://portal.revistas.bvs.br/transf.php?xsl=xsl/titles.xsl&xml=http://catserver.bireme.br/cgi-bin/wxis1660.exe/?IsisScript=../cgi-bin/catrevistas/catrevistas.xis|database_name=TITLES|list_type=title|cat_name=ALL|from=1|count=50&lang=pt&comefrom=home&home=false&task=show_magazines&request_made_adv_search=false&lang=pt&show_adv_search=false&help_file=/help_pt.htm&connector=ET&search_exp=Cad%20Saude%20Publica

Atualmente ele esta somente no teste.... para ver se funciona
https://portal.revistas.teste.bvs.br/pt/journals/?lang=pt&q=%22Cad+Saude+Publica%22

na instancia de produção será disponibilizada na segunda dia 11/11 no periodo da tarde.
https://portal.revistas.bvs.br/pt/journals/?lang=pt&q=%22Cad+Saude+Publica%22

**Comment by viniciusandrade** [comment]
@anakatiacamilo link alterado para o novo Portal de Revistas, quando possível, favor validar. Obrigado.
