### ISSUE TITLE
Mostrar todas as bases em que o registro bibliográfico pertence

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/iahx-opac#44]
@wilsonmoura há muitos registros que têm no campo  <field name="db"> mais de uma base de dados. Por exemplo, o registro http://pesquisa.bvsalud.org/portal/resource/en/biblio-846437 tem 
```
 <field name="db">LILACS</field>
 <field name="db">BRISA</field>
```
porém, na interface, só mostra LILACS. Precisamos mostrar todas as ocorrências.

**Comment by wilsonmoura** [comment]
Realizado em e362c7ed07df13b27be47a2b2340dd662b14bd31
