### ISSUE TITLE
Retirar da lista de índices da busca avançada aquelas opções que são oriundas de filtros/clusters

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/iahx-opac#48]
@marcoslmori garantir que essa mudança seja replicada em todas as instâncias
@botturam @falbrito apesar de estarmos retirando essas opções da interface, manteremos os índinces.

**Comment by botturam** [comment]
Ok. Os processamentos não serão modificados por enquanto.

**Comment by pintoros** [comment]
Segue a lista para ser retirada:
Aspecto clínico
Base de dados
Pais como assunto
Tipo de estudo
Ano de publicação* (o campo Data de publicação (pd) está disponível, porém não está habilitada a recuperação do ano como um todo ex:2017)

**Comment by viniciusandrade** [comment]
Índices retirados da configuração do Portal de Pesquisa.

Adicionamelmente foi aberto um chamado no Ocomon (5867) para retirar nas demais instâncias IAHX que tenham estes índices.
