### ISSUE TITLE
Pesquisa avançada - Campo Limite (ct)

### ISSUE THREAD

**Issue by pintoros** [bireme/iahx-opac#51]
O campo Limite reflete "somente" os limites considerados no filtro (cluster), sugiro recuperar todos os demais tipos de limites disponíveis em ct  , como alguns tipos de animais utilizados para pesquisa, apontando para este metadado e não para o filtro/cluster.

**Comment by viniciusandrade** [comment]
@pintoros 
Como a dúvida esta relacionada a composição do índice de pesquisa e não da interface criei um ticket no projeto de processamento dos índices para avaliação de viabilidade (https://github.com/bireme/db-processing/issues/103)
