### ISSUE TITLE
Pesquisa avançada - Campo ID

### ISSUE THREAD

**Issue by pintoros** [bireme/iahx-opac#53]
No campo ID é possível recuperar as opções do indice de acordo com o número digitado, sem o prefixo?
Entendo que o prefixo identifica a base de dados, mas o funcionamento desejável seria como no indice permutado. 
Ex.: ao digitar 883442, viriam as ocorrências em que este número está presente:
mdl-883442
biblio-883442
....

**Comment by viniciusandrade** [comment]
@pintoros 

Por se tratar do identificador único não é permitido pela ferramenta gerar partes de recuperação no mesmo índice ID.

No entanto informo que atualmente já é possível realizar a recuperação das várias ocorrências onde o número do identificador esta presente bastando usar o símbolo *. Exemplo:

id:*-883442
