### ISSUE TITLE
Pesquisa avançada - Campo Título da Revista

### ISSUE THREAD

**Issue by alvesmarilda** [bireme/iahx-opac#57]
Não é possível recuperar o título da Revista.

http://pesquisa.bvsalud.org/portal/advanced/?lang=pt#
Busca Avançada

J. appl. oral sci  -  Revista

Exemplo: http://pesquisa.bvsalud.org/portal/?lang=pt&q=%28ta%3A%28J.+appl.+oral+sci%29%29
Não foram encontrados documentos para sua pesquisa

Obrigada!

**Comment by botturam** [comment]
Os problemas de pesquisa foram esclarecidas pelo Vinícius, tratando-se de questões de desenvolvimento no módulo de pesquisa avançada do IAHx.

Marilda ficou de abrir um novo chamado à área de desenvolvimento, solicitando as devidas correções.
