### ISSUE TITLE
Refatoramento de código para uso do protocolo HTTPS

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/iahx-opac#62]
Pontos que justificam a implementação do protocolo para pesquisa:

- O Google esta desde meados de 2018 marcando todos os sites que não utilizam HTTPS como "não seguros"
- Mesmo após a implementação do HTTPS no Portal da BVS o Google Chrome ainda aponta o domínio como não totalmente seguro devido ao formulário de pesquisa que utiliza o dominio não seguro da pesquisa.bvsalud.org
- Melhor posicionamento no resultados das buscas do Google (pagerank)

Possíveis pontos de impacto:

1. Estatísticas do Google Analytics - probabilidade baixa pois não foram detectados problemas com os demais sites que foram alterados para HTTPS (ex. bvsalud.org e FI-ADMIN)
2. Links de sites externos para a pesquisa da BVS - probabilidade baixa pois existirá o redirecionamento das URLs com HTTP para HTTPS
3. Formulários de busca externo - probabilidade alta 
4. Widget de busca do plugin BVS-Site Wordpress - probabilidade alta
5. Caixa de busca do serviço MinhaBVS - probabilidade alta

**Comment by renatomurasaki** [comment]
@viniciusandrade obrigado pela análise de risco sobre a implementação de SSL no iAHx.

@marcoslmori Favor preparar nota para a RedDes sobre o item 3, contendo o porque que vamos alterar de HTTP para HTTPS, o impacto e as ações de correção. 

@wilsonmoura Favor avaliar as atividades necessárias para os itens 4 e 5.

@viniciusandrade @marcoslmori @wilsonmoura vejam juntos em qual sprint podemos implementar estas atividades para tornar o iAHx HTTPS, de maneira a sincronizar as ações de acordo com as demandas atuais. Me parece que poderia ser na semana de 18/jan.

**Comment by wilsonmoura** [comment]
@renatomurasaki segue descrição das atividades 4 e 5:

4. bireme/bvs-site-wp-plugin#44
5. Esse ajuste é feito no arquivo de configuração da MinhaBVS

**Comment by viniciusandrade** [comment]
@marcoslmori solicitei a habilitação do protocolo HTTPS no ambiente de testes. Favor realizar testes para o item 3 com os temas que possuem widget de texto com formulário de pesquisa.

**Comment by viniciusandrade** [comment]
Para instâncias da versão 2.x será necessário adicicionar o parâmetro `<use_https>true</use_https>` no **config.xml** e atualizar o arquivo **environment.php**

**Comment by viniciusandrade** [comment]
Processo de testes e implementação documentado pelo @marcoslmori em http://wiki.bireme.org/intranet/index.php/Implementacao_do_protocolo_SSL_na_instancias_de_IAHX
