### ISSUE TITLE
Título abreviado LILACS não encontrado na pesquisa

### ISSUE THREAD

**Issue by suelisuga** [bireme/iahx-opac#63]
Prezados,

Solução encontrada no issue #55  "Busca por título abreviado LILACS com resultado vazio" não resolveu completamente o problema, pois há diferenças nos títulos abreviados LILACS e MEDLINE além de maiúsculas, pontos e acentos.

Exemplo:
título LILACS: Rev. Fac. Cienc. Méd. (Córdoba)
título MEDLINE: Rev Fac Cien Med Univ Nac Cordoba

Solicito a criação de um índice que mescle títulos abreviados LILACS e MEDLINE porque erro sempre ocorre para nós que utilizamos o padrão ISSN e fazemos nossa rede utilizar esse título abreviado.

Obrigada!
Sueli M Yano Suga
BIREME/OPAS/OMS

**Comment by botturam** [comment]
Sueli,

você poderia indicar algum id de registro LILACS com o campo de revista "Rev. Fac. Cienc. Méd. (Córdoba)"? Não encontrei registro desta revista na LILACS

**Comment by botturam** [comment]
A Previsão para publicação em produção é segunda-feira, 04 de março.

**Comment by botturam** [comment]
Processamento concluído, disponível em produção. Realizei os seguintes testes: 

LIL - ta:"Braz dent. J"
MDL - ta:"Braz dent J"

LIL - ta:"Gac. méd. Caracas"
MDL - ta:"Gac méd Caracas"

LIL - ta:"Rev Bras. Otorrinolaringol"
MDL - ta:"Rev Bras Otorrinolaringol"
