### ISSUE TITLE
Revisar CSS de print da página

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/iahx-opac#73]
A opção de imprimir carrega a CSS "print.css" responsável em esconder os blocos da página que não precisam ser impressos. 

Esta CSS precisa ser revisada para o novo template de apresentação #69.

**Comment by marcioalvessilva** [comment]
Alterações para impressão - 575ac59 - commit 04478c449f4039d0e7d07f7785dd3cf77ecdb39f
