### ISSUE TITLE
Revisão página de interna de detalhes 

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/iahx-opac#74]
Incorporar na apresentação do resumo a opção de tabs para separação por idioma conforme exemplo:

http://pesquisa.bvsalud.org/portal/resource/pt/biblio-984141

Relacionado: #69

**Comment by marcioalvessilva** [comment]
Inserido Tabs de Resumos - 7409e4d commit 575ac597f022733b0ca798ba25b593ad7d84e535
