### ISSUE TITLE
Aplicar novo layout para página "Localizar descritor de assunto"

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/iahx-opac#75]
Ajustar página a seguinte página para o novo template:

http://pesquisa.bvsalud.org/portal/decs-locator/?lang=pt&tree_id=D&tree_id=D06

**Comment by marcioalvessilva** [comment]
Desenvolvida página de Hierarquia -  be11fc6 commit 57b1a18935bb52deddc2d9b3714ffd9319ed1027
