### ISSUE TITLE
Ajustes novo template

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/iahx-opac#77]
- [x] Aumentar caixa de seleção de índices no formulário de pequisa (header)
- [x] Diminuir tamanho do div da seta que realiza a rolagem para cima da tela
- [x] Remover estilo de link dos itens de filtro
- [x] Tornar o botão Filtrar fixo na página 
- [x] Ajustar a página de resultados para impressão

**Comment by marcioalvessilva** [comment]
Todos os itens solicitados foram finalizados
