### ISSUE TITLE
Configuração de filtros

### ISSUE THREAD

**Issue by pintoros** [bireme/iahx-opac#78]
Na página de resultado mostrar como defaut os filtros abaixo, abertos:
- Assunto principal
- Tipo de estudo
- País/Região como assunto
Todos os filtros disponíveis devem ser apresentados no recurso de configuração de filtros.

**Comment by viniciusandrade** [comment]
Implementado em https://github.com/bireme/iahx-opac/commit/3db49046265ed9a851fb9b0d0f4922069bc078f8
