### ISSUE TITLE
Layout dos botões de serviço na página de detalhe

### ISSUE THREAD

**Issue by pintoros** [bireme/iahx-opac#81]
Alterar layout dos botões no detalhe da referência
[Texto completo]
[Minha BVS]

**Comment by marcioalvessilva** [comment]
Css mais alterações no arquivo colunaDirInter.php
https://github.com/bireme/mockups/commit/0974ea2959bb8ae9b7c9fb2deaae5fd0a9f08503

**Comment by viniciusandrade** [comment]
Implementado em https://github.com/bireme/iahx-opac/commit/3a105efe71b6d02a2e9268223adb07183c21dd21
