### ISSUE TITLE
Incluir redes sociais no detalhe da referência

### ISSUE THREAD

**Issue by pintoros** [bireme/iahx-opac#82]
Incluir opções de redes sociais no detalhe da referência de acordo com o desenho proposto pela consultora:
Facebook
Twitter
LinkedIn
WhatsApp

**Comment by marcioalvessilva** [comment]
Inclusão do arquivo rede social.php no arquivo interna.php
https://github.com/bireme/mockups/commit/0974ea2959bb8ae9b7c9fb2deaae5fd0a9f08503

**Comment by viniciusandrade** [comment]
Implementado em https://github.com/bireme/iahx-opac/commit/047d536feadae8763f765d12c4b439921eac9e42
