### ISSUE TITLE
Labels - ajustes na página de resultado

### ISSUE THREAD

**Issue by pintoros** [bireme/iahx-opac#83]
Mudar o label **Filtrar**    **Configurações**  para  **Adicionar filtros**
Obs. A palavra a frente e  configurações deve ser excluída.
Manter o botão [Filtrar] em baixo
Traduções:
Adicionar filtros
Añadir filtros
Add filters
Ajouter des filtres

-------------------------
Alterar labels da area Sua seleção

Selecão de referências / Sélection de références /Selection of references / Selección de referencias
- Listar referências  / Liste des références / List references / Listar referencias
- Limpar seleção

-----------------------

Incluir Mostrar /Montrer / Show / Mostrar na seleção de páginas 20/50/100

**Comment by viniciusandrade** [comment]
Ajustes aplicados (https://github.com/bireme/iahx-opac/commit/6f3b7c364d5a052f2034a56e008f6a7e2a7853ff)
