### ISSUE TITLE
Sinal para expandir filtros

### ISSUE THREAD

**Issue by pintoros** [bireme/iahx-opac#85]
Por favor trocar o sinal atual para expandir os filtros para seta, pois é mais intuitivo.

**Comment by marcioalvessilva** [comment]
Modificado Icones (+ e -) por setas (Cima e Baixo)
https://github.com/bireme/mockups/commit/e817fd8534814b083b62319ca445d4ee1b1cb62d

**Comment by viniciusandrade** [comment]
Implementado em https://github.com/bireme/iahx-opac/commit/6210da84eb6073ec5bb42333c8a2826c5a413f85
