### ISSUE TITLE
Botão pesquisar

### ISSUE THREAD

**Issue by pintoros** [bireme/iahx-opac#89]
Substituir botão pesquisar por lupa abaixo da caixa "Detalhe da pesquisa"

**Comment by marcioalvessilva** [comment]
Trocar texto por icone fontawesome

https://github.com/bireme/mockups/commit/e43ac24dc13e2dc322734fc0ed6ffedb57af55a1#diff-0479db8d98a53c19a77b617b35fbb780R27
