### ISSUE TITLE
Layout - Diferenciar área de serviços

### ISSUE THREAD

**Issue by pintoros** [bireme/iahx-opac#90]
Diferenciar o fundo/layout da área de serviços (emal, exportar, imprimir....) 
E criar label para esta área:
Enviar para:
Send to:
Envoyer à:

**Comment by marcioalvessilva** [comment]
Inserir Titulo no grupo de botões
https://github.com/bireme/mockups/commit/e43ac24dc13e2dc322734fc0ed6ffedb57af55a1#diff-0479db8d98a53c19a77b617b35fbb780R8

https://github.com/bireme/mockups/commit/e43ac24dc13e2dc322734fc0ed6ffedb57af55a1#diff-1f67a20dde93750b6171ae814ee283b0R6

style css
https://github.com/bireme/mockups/commit/e43ac24dc13e2dc322734fc0ed6ffedb57af55a1#diff-6513d09f30f0ac8ba71e4625317dd13bR13
