### ISSUE TITLE
Seleção de referências

### ISSUE THREAD

**Issue by pintoros** [bireme/iahx-opac#91]
Letra muito pequena nos comandos abaixo dessa opção. (Ver arquivo de alteração de labels)

**Comment by marcioalvessilva** [comment]
Alterar css

Style
https://github.com/bireme/mockups/commit/df9ced2c1c564891f9cafa71110583d6f5de11b3#diff-6513d09f30f0ac8ba71e4625317dd13bR49

**Comment by viniciusandrade** [comment]
CSS atualizada.
