### ISSUE TITLE
Layout - Botões

### ISSUE THREAD

**Issue by pintoros** [bireme/iahx-opac#92]
Os botões assemelham-se a cabeçalhos.
Não apresentam o mesmo comportamento referente a cor.
O mesmo botão muda de tamanho (ex. botão filtrar)
Dentro da opção "Adicionar filtros" o botão aplicar também tem padrão diferente.
Limpar todos é botão

![image](https://user-images.githubusercontent.com/29313904/63057220-211c1e80-bec0-11e9-856a-46365f6a6fcd.png)

![image](https://user-images.githubusercontent.com/29313904/63057606-01392a80-bec1-11e9-8417-c211a96daceb.png)

**Comment by marcioalvessilva** [comment]
Remover trocar classe btn-dark por btnBlue
https://github.com/bireme/mockups/commit/e43ac24dc13e2dc322734fc0ed6ffedb57af55a1#diff-abcb8d4667d2d16924ddec401366350bR69

Alterar CSS
https://github.com/bireme/mockups/commit/e43ac24dc13e2dc322734fc0ed6ffedb57af55a1#diff-6513d09f30f0ac8ba71e4625317dd13bR6

https://github.com/bireme/mockups/commit/e43ac24dc13e2dc322734fc0ed6ffedb57af55a1#diff-6513d09f30f0ac8ba71e4625317dd13bR9

https://github.com/bireme/mockups/commit/e43ac24dc13e2dc322734fc0ed6ffedb57af55a1#diff-6513d09f30f0ac8ba71e4625317dd13bR71
