### ISSUE TITLE
Banner

### ISSUE THREAD

**Issue by pintoros** [bireme/iahx-opac#93]
Falta inclui o nome do Portal Regional da BVS no banner al lado do logo

**Comment by marcioalvessilva** [comment]
Inserir duas linhas de título

index
https://github.com/bireme/mockups/commit/e43ac24dc13e2dc322734fc0ed6ffedb57af55a1#diff-a3e49808bfabf2e0e0fa0ef4eaedce07R9

style
https://github.com/bireme/mockups/commit/e43ac24dc13e2dc322734fc0ed6ffedb57af55a1#diff-6513d09f30f0ac8ba71e4625317dd13bR40
style breakpoint
https://github.com/bireme/mockups/commit/e43ac24dc13e2dc322734fc0ed6ffedb57af55a1#diff-6513d09f30f0ac8ba71e4625317dd13bR167
