### ISSUE TITLE
Tamanho da letra

### ISSUE THREAD

**Issue by pintoros** [bireme/iahx-opac#96]
Nos comandos da direita e opções de navegação,  a letra está muito pequena.

![image](https://user-images.githubusercontent.com/29313904/63058362-e5cf1f00-bec2-11e9-9e59-88c461c8f238.png)
![image](https://user-images.githubusercontent.com/29313904/63058431-17e08100-bec3-11e9-84e2-45a67adcc98a.png)

**Comment by viniciusandrade** [comment]
Ajustes realizados na CSS pelo @marcioalvessilva.
