### ISSUE TITLE
Negrito no título dos documentos

### ISSUE THREAD

**Issue by pintoros** [bireme/iahx-opac#97]
Tirar o negrito do título dos documentos

**Comment by marcioalvessilva** [comment]
Remover bold
https://github.com/bireme/mockups/commit/e43ac24dc13e2dc322734fc0ed6ffedb57af55a1#diff-8acfecda3d220970ebcc01e181deb486R34

Modificar Style
https://github.com/bireme/mockups/commit/e43ac24dc13e2dc322734fc0ed6ffedb57af55a1#diff-6513d09f30f0ac8ba71e4625317dd13bR32
