### ISSUE TITLE
Número na referência

### ISSUE THREAD

**Issue by pintoros** [bireme/iahx-opac#98]
Incluir número nas referências

**Comment by marcioalvessilva** [comment]
Inserir Números
https://github.com/bireme/mockups/commit/e43ac24dc13e2dc322734fc0ed6ffedb57af55a1#diff-9761e18052d52b5913ef8cf2dfe27787R44

Style
https://github.com/bireme/mockups/commit/e43ac24dc13e2dc322734fc0ed6ffedb57af55a1#diff-6513d09f30f0ac8ba71e4625317dd13bR60

https://github.com/bireme/mockups/commit/e43ac24dc13e2dc322734fc0ed6ffedb57af55a1#diff-6513d09f30f0ac8ba71e4625317dd13bR69
