### ISSUE TITLE
Layout - Caixa de busca

### ISSUE THREAD

**Issue by pintoros** [bireme/iahx-opac#99]
Aumentar a letra para digitação

Puxar a barra da caixa conforme imagem, liberando mais espaço util

![image](https://user-images.githubusercontent.com/29313904/63059620-4ca20780-bec6-11e9-948d-1c228c6e8805.png)

Tirar o excesso de espaço no início e fim da caixa

![image](https://user-images.githubusercontent.com/29313904/63059769-ac98ae00-bec6-11e9-94b6-ed76f6320b72.png)

**Comment by marcioalvessilva** [comment]
Espaço minimo foi deixado para manter o layout fluido
Elementos de acessibilidade iram preencher mais espaços

**Comment by viniciusandrade** [comment]
Integrado ao template.
